// this is autogenerated file, do not edit it.
#include "ficus/ficus.h"

FX_EXTERN_C bool _fx_M4CharFM7isalphaB1C(char_ c,
                                         void* fx_fv)
{
   return fx_isalpha(c);
}

FX_EXTERN_C bool _fx_M4CharFM7isalnumB1C(char_ c,
                                         void* fx_fv)
{
   return fx_isalnum(c);
}

FX_EXTERN_C bool _fx_M4CharFM7isdigitB1C(char_ c,
                                         void* fx_fv)
{
   return fx_isdigit(c);
}

FX_EXTERN_C bool _fx_M4CharFM7isspaceB1C(char_ c,
                                         void* fx_fv)
{
   return fx_isspace(c);
}

FX_EXTERN_C int fx_init_Char(void)
{
   int fx_status = 0;
   return fx_status;
}

FX_EXTERN_C void fx_deinit_Char(void)
{
}
