
// this is autogenerated file, do not edit it.
#include "ficus/ficus.h"

int _FX_EXN_E22Dynvec__EmptyDynVector = 0;
fx_exn_info_t _fx_E22Dynvec__EmptyDynVector_info = {0};
fx_exn_t _fx_E22Dynvec__EmptyDynVectorv = {0};
FX_EXTERN_C int fx_init_Dynvec(void)
{
   FX_REG_SIMPLE_EXN("Dynvec.EmptyDynVector", _FX_EXN_E22Dynvec__EmptyDynVector, _fx_E22Dynvec__EmptyDynVector_info,
      _fx_E22Dynvec__EmptyDynVectorv);
   int fx_status = 0;
   return fx_status;
}

FX_EXTERN_C void fx_deinit_Dynvec(void)
{

}

