
// this is autogenerated file, do not edit it.
#include "ficus/ficus.h"


#include <stdio.h>

typedef struct _fx_R7File__t {
   fx_cptr_t handle;
} _fx_R7File__t;

typedef struct {
   int_ rc;
   int_ data;
} _fx_E4Exit_data_t;

typedef struct {
   int_ rc;
   fx_str_t data;
} _fx_E4Fail_data_t;

static void _fx_free_R7File__t(struct _fx_R7File__t* dst)
{
   fx_free_cptr(&dst->handle);
}

static void _fx_copy_R7File__t(struct _fx_R7File__t* src, struct _fx_R7File__t* dst)
{
   fx_copy_cptr(src->handle, &dst->handle);
}

static void _fx_make_R7File__t(fx_cptr_t r_handle, struct _fx_R7File__t* fx_result)
{
   fx_copy_cptr(r_handle, &fx_result->handle);
}

int_ _fx_g14File__SEEK_SET = 
(int)SEEK_SET
;
int_ _fx_g15File__SEEK_CURR = 
(int)SEEK_CUR
;
int_ _fx_g14File__SEEK_END = 
(int)SEEK_END
;
_fx_R7File__t _fx_g12File__stdout = {  };
FX_EXTERN_C int _fx_M4FileFM13get_stdstreamRM1t1i(int_ i, struct _fx_R7File__t* fx_result, void* fx_fv)
{
   
if(i != 0 && i != 1 && i != 2)
        FX_FAST_THROW_RET(FX_EXN_NullFileError);
    fx_result->handle = fx_get_stdstream(i);
    return FX_OK;

}

FX_EXTERN_C int _fx_M4FileFM5open_p3SSB(fx_str_t* fname, fx_str_t* mode, bool ispipe, fx_cptr_t* fx_result, void* fx_fv)
{
   
fx_cstr_t fname_, mode_;
    int fx_status = fx_str2cstr(fname, &fname_, 0, 0);
    if (fx_status >= 0) {
        fx_status = fx_str2cstr(mode, &mode_, 0, 0);
        if (fx_status >= 0) {
            FILE* f = ispipe ?
            #ifdef _WIN32
                _popen(fname_.data, mode_.data) :
            #else
                popen(fname_.data, mode_.data) :
            #endif
                fopen(fname_.data, mode_.data);
            if (f) {
                fx_status = fx_make_cptr(f, (ispipe ? fx_pipe_destructor :
                                        fx_file_destructor), fx_result);
            }
            else {
                fx_status = FX_SET_EXN_FAST(FX_EXN_FileOpenError);
            }
            fx_free_cstr(&mode_);
        }
        fx_free_cstr(&fname_);
    }
    return fx_status;

}

FX_EXTERN_C void _fx_M4FileFM5closev1RM1t(struct _fx_R7File__t* f, void* fx_fv)
{
   
if(f->handle && f->handle->ptr) {
        f->handle->free_f(f->handle->ptr);
        f->handle->ptr = 0;
    }

}

FX_EXTERN_C int _fx_M4FileFM5flushv1RM1t(struct _fx_R7File__t* f, void* fx_fv)
{
   
if(!f->handle || !f->handle->ptr)
        FX_FAST_THROW_RET(FX_EXN_NullFileError);
    fflush((FILE*)(f->handle->ptr));
    return FX_OK;

}

FX_EXTERN_C int _fx_M4FileFM5printv2RM1tS(struct _fx_R7File__t* f, fx_str_t* x, void* fx_fv)
{
   
if(!f->handle || !f->handle->ptr)
        FX_FAST_THROW_RET(FX_EXN_NullFileError);
    return fx_fputs((FILE*)(f->handle->ptr), x);

}

FX_EXTERN_C int _fx_M4FileFM6readlnS1RM1t(struct _fx_R7File__t* f, fx_str_t* fx_result, void* fx_fv)
{
   
if(!f->handle || !f->handle->ptr)
        FX_FAST_THROW_RET(FX_EXN_NullFileError);
    return fx_fgets((FILE*)(f->handle->ptr), fx_result);

}

FX_EXTERN_C int _fx_M4FileFM9read_utf8S1S(fx_str_t* fname, fx_str_t* fx_result, void* fx_fv)
{
   
fx_cstr_t fname_;
    int fx_status = fx_str2cstr(fname, &fname_, 0, 0);
    if (fx_status >= 0) {
        FILE* f = fopen(fname_.data, "rb");
        if (f) {
            fseek(f, 0, SEEK_END);
            int_ size = (int_)ftell(f);
            fseek(f, 0, SEEK_SET);
            fx_cstr_t buf;
            fx_status = fx_make_cstr(0, size, &buf);
            if (fx_status >= 0) {
                int_ count = (int_)fread(buf.data, 1, (size_t)size, f);
                if (count == size) {
                    fx_status = fx_cstr2str(buf.data, size, fx_result);
                } else {
                    fx_status = FX_SET_EXN_FAST(FX_EXN_IOError);
                }
                fx_free_cstr(&buf);
            }
            fclose(f);
        } else {
            fx_status = FX_SET_EXN_FAST(FX_EXN_FileOpenError);
        }
        fx_free_cstr(&fname_);
    }
    return fx_status;

}

FX_EXTERN_C int _fx_M4FileFM10write_utf8v2SS(fx_str_t* fname, fx_str_t* text, void* fx_fv)
{
   
fx_cstr_t fname_;
    int fx_status = fx_str2cstr(fname, &fname_, 0, 0);
    if (fx_status >= 0) {
        FILE* f = fopen(fname_.data, "wb");
        if (f) {
            fx_cstr_t buf;
            fx_status = fx_str2cstr(text, &buf, 0, 0);
            if (fx_status >= 0) {
                int_ count = (int_)fwrite(buf.data, 1, buf.length, f);
                if (count != buf.length)
                    fx_status = FX_SET_EXN_FAST(FX_EXN_IOError);
                fx_free_cstr(&buf);
            }
            fclose(f);
            if (fx_status < 0)
                remove(fname_.data);
        } else {
            fx_status = FX_SET_EXN_FAST(FX_EXN_FileOpenError);
        }
        fx_free_cstr(&fname_);
    }
    return fx_status;

}

FX_EXTERN_C int fx_init_File(void)
{
   _fx_R7File__t res_0 = {  };
   _fx_R7File__t res_1 = {  };
   int fx_status = 0;
   FX_CALL(_fx_M4FileFM13get_stdstreamRM1t1i(0, &res_0, 0), _fx_cleanup);
   FX_CALL(_fx_M4FileFM13get_stdstreamRM1t1i(1, &_fx_g12File__stdout, 0), _fx_cleanup);
   FX_CALL(_fx_M4FileFM13get_stdstreamRM1t1i(2, &res_1, 0), _fx_cleanup);

_fx_cleanup: ;
   _fx_free_R7File__t(&res_0);
   _fx_free_R7File__t(&res_1);
   return fx_status;
}

FX_EXTERN_C void fx_deinit_File(void)
{
   _fx_free_R7File__t(&_fx_g12File__stdout);
}

