
// this is autogenerated file, do not edit it.
#include "ficus/ficus.h"

FX_EXTERN_C int _fx_M7HashsetFM9makeindexA1i1i(int_ size_0, fx_arr_t* fx_result, void* fx_fv)
{
   int fx_status = 0;
   int_* dstptr_0 = 0;
   {
      const int_ shape_0[] = { size_0 };
      FX_CALL(fx_make_arr(1, shape_0, sizeof(int_), 0, 0, 0, fx_result), _fx_cleanup);
   }
   dstptr_0 = (int_*)fx_result->data;
   for (int_ i_0 = 0; i_0 < size_0; i_0++, dstptr_0++) {
      *dstptr_0 = 0;
   }

_fx_cleanup: ;
   return fx_status;
}

FX_EXTERN_C int fx_init_Hashset(void)
{
   int fx_status = 0;
   return fx_status;
}

FX_EXTERN_C void fx_deinit_Hashset(void)
{

}

