
// this is autogenerated file, do not edit it.
#include "ficus/ficus.h"


#include <math.h>
#include <float.h>

float _fx_g17Math__FLT_EPSILON = 
FLT_EPSILON
;
double _fx_g17Math__DBL_EPSILON = 
DBL_EPSILON
;
FX_EXTERN_C double _fx_M4MathFM3powd2dd(double x, double y, void* fx_fv)
{ 
return pow(x, y);

}

FX_EXTERN_C int fx_init_Math(void)
{ int fx_status = 0; return fx_status;
}

FX_EXTERN_C void fx_deinit_Math(void)
{
}

