
// this is autogenerated file, do not edit it.
#include "ficus/ficus.h"

typedef struct _fx_LS_data_t {
   int_ rc;
   struct _fx_LS_data_t* tl;
   fx_str_t hd;
} _fx_LS_data_t, *_fx_LS;

typedef struct _fx_Nt6option1i {
   int tag;
   union {
      int_ Some;
   } u;
} _fx_Nt6option1i;

typedef struct _fx_FPS1B {
   int (*fp)(bool, fx_str_t*, void*);
   fx_fcv_t* fcv;
} _fx_FPS1B;

typedef struct _fx_N17Options__optval_t {
   int tag;
   union {
      bool OptBool;
      int_ OptInt;
      fx_str_t OptString;
   } u;
} _fx_N17Options__optval_t;

typedef struct _fx_T2SN17Options__optval_t {
   fx_str_t t0;
   struct _fx_N17Options__optval_t t1;
} _fx_T2SN17Options__optval_t;

typedef struct _fx_LT2SN17Options__optval_t_data_t {
   int_ rc;
   struct _fx_LT2SN17Options__optval_t_data_t* tl;
   struct _fx_T2SN17Options__optval_t hd;
} _fx_LT2SN17Options__optval_t_data_t, *_fx_LT2SN17Options__optval_t;

typedef struct _fx_R18Options__options_t {
   struct _fx_LS_data_t* app_args;
   fx_str_t app_filename;
   bool arch64;
   bool force_rebuild;
   fx_str_t build_dir;
   fx_str_t build_rootdir;
   fx_str_t cflags;
   fx_str_t clibs;
   bool compile_by_cpp;
   fx_str_t filename;
   bool gen_c;
   struct _fx_LS_data_t* include_path;
   bool debug;
   struct _fx_LT2SN17Options__optval_t_data_t* defines;
   int_ optim_iters;
   int_ inline_thresh;
   bool enable_openmp;
   bool relax;
   bool use_preamble;
   bool make_app;
   int_ optimize_level;
   fx_str_t output_name;
   bool print_ast0;
   bool print_ast;
   bool print_k0;
   bool print_k;
   bool print_tokens;
   bool print_resolve;
   bool run_app;
   bool verbose;
   bool W_unused;
   bool W_implicit_rettype;
   bool W_implicit_rettype_all;
   bool Werror;
   int_ max_errors;
   fx_str_t diag_format;
} _fx_R18Options__options_t;

typedef struct _fx_Ta2S {
   fx_str_t t0;
   fx_str_t t1;
} _fx_Ta2S;

typedef struct {
   int_ rc;
   int_ data;
} _fx_E4Exit_data_t;

typedef struct {
   int_ rc;
   fx_str_t data;
} _fx_E4Fail_data_t;

static void _fx_free_LS(struct _fx_LS_data_t** dst)
{
   FX_FREE_LIST_IMPL(_fx_LS, fx_free_str);
}

static int _fx_cons_LS(fx_str_t* hd, struct _fx_LS_data_t* tl, bool addref_tl, struct _fx_LS_data_t** fx_result)
{
   FX_MAKE_LIST_IMPL(_fx_LS, fx_copy_str);
}

static void _fx_free_N17Options__optval_t(struct _fx_N17Options__optval_t* dst)
{
   switch (dst->tag) {
   case 3:
      fx_free_str(&dst->u.OptString); break;
   default:
      ;
   }
   dst->tag = 0;
}

static void _fx_copy_N17Options__optval_t(struct _fx_N17Options__optval_t* src, struct _fx_N17Options__optval_t* dst)
{
   dst->tag = src->tag;
   switch (src->tag) {
   case 3:
      fx_copy_str(&src->u.OptString, &dst->u.OptString); break;
   default:
      dst->u = src->u;
   }
}

static void _fx_free_T2SN17Options__optval_t(struct _fx_T2SN17Options__optval_t* dst)
{
   fx_free_str(&dst->t0);
   _fx_free_N17Options__optval_t(&dst->t1);
}

static void _fx_copy_T2SN17Options__optval_t(struct _fx_T2SN17Options__optval_t* src, struct _fx_T2SN17Options__optval_t* dst)
{
   fx_copy_str(&src->t0, &dst->t0);
   _fx_copy_N17Options__optval_t(&src->t1, &dst->t1);
}

static void _fx_make_T2SN17Options__optval_t(
   fx_str_t* t0,
   struct _fx_N17Options__optval_t* t1,
   struct _fx_T2SN17Options__optval_t* fx_result)
{
   fx_copy_str(t0, &fx_result->t0);
   _fx_copy_N17Options__optval_t(t1, &fx_result->t1);
}

static void _fx_free_LT2SN17Options__optval_t(struct _fx_LT2SN17Options__optval_t_data_t** dst)
{
   FX_FREE_LIST_IMPL(_fx_LT2SN17Options__optval_t, _fx_free_T2SN17Options__optval_t);
}

static int _fx_cons_LT2SN17Options__optval_t(
   struct _fx_T2SN17Options__optval_t* hd,
   struct _fx_LT2SN17Options__optval_t_data_t* tl,
   bool addref_tl,
   struct _fx_LT2SN17Options__optval_t_data_t** fx_result)
{
   FX_MAKE_LIST_IMPL(_fx_LT2SN17Options__optval_t, _fx_copy_T2SN17Options__optval_t);
}

static void _fx_free_R18Options__options_t(struct _fx_R18Options__options_t* dst)
{
   _fx_free_LS(&dst->app_args);
   fx_free_str(&dst->app_filename);
   fx_free_str(&dst->build_dir);
   fx_free_str(&dst->build_rootdir);
   fx_free_str(&dst->cflags);
   fx_free_str(&dst->clibs);
   fx_free_str(&dst->filename);
   _fx_free_LS(&dst->include_path);
   _fx_free_LT2SN17Options__optval_t(&dst->defines);
   fx_free_str(&dst->output_name);
   fx_free_str(&dst->diag_format);
}

static void _fx_copy_R18Options__options_t(struct _fx_R18Options__options_t* src, struct _fx_R18Options__options_t* dst)
{
   FX_COPY_PTR(src->app_args, &dst->app_args);
   fx_copy_str(&src->app_filename, &dst->app_filename);
   dst->arch64 = src->arch64;
   dst->force_rebuild = src->force_rebuild;
   fx_copy_str(&src->build_dir, &dst->build_dir);
   fx_copy_str(&src->build_rootdir, &dst->build_rootdir);
   fx_copy_str(&src->cflags, &dst->cflags);
   fx_copy_str(&src->clibs, &dst->clibs);
   dst->compile_by_cpp = src->compile_by_cpp;
   fx_copy_str(&src->filename, &dst->filename);
   dst->gen_c = src->gen_c;
   FX_COPY_PTR(src->include_path, &dst->include_path);
   dst->debug = src->debug;
   FX_COPY_PTR(src->defines, &dst->defines);
   dst->optim_iters = src->optim_iters;
   dst->inline_thresh = src->inline_thresh;
   dst->enable_openmp = src->enable_openmp;
   dst->relax = src->relax;
   dst->use_preamble = src->use_preamble;
   dst->make_app = src->make_app;
   dst->optimize_level = src->optimize_level;
   fx_copy_str(&src->output_name, &dst->output_name);
   dst->print_ast0 = src->print_ast0;
   dst->print_ast = src->print_ast;
   dst->print_k0 = src->print_k0;
   dst->print_k = src->print_k;
   dst->print_tokens = src->print_tokens;
   dst->print_resolve = src->print_resolve;
   dst->run_app = src->run_app;
   dst->verbose = src->verbose;
   dst->W_unused = src->W_unused;
   dst->W_implicit_rettype = src->W_implicit_rettype;
   dst->W_implicit_rettype_all = src->W_implicit_rettype_all;
   dst->Werror = src->Werror;
   dst->max_errors = src->max_errors;
   fx_copy_str(&src->diag_format, &dst->diag_format);
}

static void _fx_make_R18Options__options_t(
   struct _fx_LS_data_t* r_app_args,
   fx_str_t* r_app_filename,
   bool r_arch64,
   bool r_force_rebuild,
   fx_str_t* r_build_dir,
   fx_str_t* r_build_rootdir,
   fx_str_t* r_cflags,
   fx_str_t* r_clibs,
   bool r_compile_by_cpp,
   fx_str_t* r_filename,
   bool r_gen_c,
   struct _fx_LS_data_t* r_include_path,
   bool r_debug,
   struct _fx_LT2SN17Options__optval_t_data_t* r_defines,
   int_ r_optim_iters,
   int_ r_inline_thresh,
   bool r_enable_openmp,
   bool r_relax,
   bool r_use_preamble,
   bool r_make_app,
   int_ r_optimize_level,
   fx_str_t* r_output_name,
   bool r_print_ast0,
   bool r_print_ast,
   bool r_print_k0,
   bool r_print_k,
   bool r_print_tokens,
   bool r_print_resolve,
   bool r_run_app,
   bool r_verbose,
   bool r_W_unused,
   bool r_W_implicit_rettype,
   bool r_W_implicit_rettype_all,
   bool r_Werror,
   int_ r_max_errors,
   fx_str_t* r_diag_format,
   struct _fx_R18Options__options_t* fx_result)
{
   FX_COPY_PTR(r_app_args, &fx_result->app_args);
   fx_copy_str(r_app_filename, &fx_result->app_filename);
   fx_result->arch64 = r_arch64;
   fx_result->force_rebuild = r_force_rebuild;
   fx_copy_str(r_build_dir, &fx_result->build_dir);
   fx_copy_str(r_build_rootdir, &fx_result->build_rootdir);
   fx_copy_str(r_cflags, &fx_result->cflags);
   fx_copy_str(r_clibs, &fx_result->clibs);
   fx_result->compile_by_cpp = r_compile_by_cpp;
   fx_copy_str(r_filename, &fx_result->filename);
   fx_result->gen_c = r_gen_c;
   FX_COPY_PTR(r_include_path, &fx_result->include_path);
   fx_result->debug = r_debug;
   FX_COPY_PTR(r_defines, &fx_result->defines);
   fx_result->optim_iters = r_optim_iters;
   fx_result->inline_thresh = r_inline_thresh;
   fx_result->enable_openmp = r_enable_openmp;
   fx_result->relax = r_relax;
   fx_result->use_preamble = r_use_preamble;
   fx_result->make_app = r_make_app;
   fx_result->optimize_level = r_optimize_level;
   fx_copy_str(r_output_name, &fx_result->output_name);
   fx_result->print_ast0 = r_print_ast0;
   fx_result->print_ast = r_print_ast;
   fx_result->print_k0 = r_print_k0;
   fx_result->print_k = r_print_k;
   fx_result->print_tokens = r_print_tokens;
   fx_result->print_resolve = r_print_resolve;
   fx_result->run_app = r_run_app;
   fx_result->verbose = r_verbose;
   fx_result->W_unused = r_W_unused;
   fx_result->W_implicit_rettype = r_W_implicit_rettype;
   fx_result->W_implicit_rettype_all = r_W_implicit_rettype_all;
   fx_result->Werror = r_Werror;
   fx_result->max_errors = r_max_errors;
   fx_copy_str(r_diag_format, &fx_result->diag_format);
}

static void _fx_free_Ta2S(struct _fx_Ta2S* dst)
{
   fx_free_str(&dst->t0);
   fx_free_str(&dst->t1);
}

static void _fx_copy_Ta2S(struct _fx_Ta2S* src, struct _fx_Ta2S* dst)
{
   fx_copy_str(&src->t0, &dst->t0);
   fx_copy_str(&src->t1, &dst->t1);
}

static void _fx_make_Ta2S(fx_str_t* t0, fx_str_t* t1, struct _fx_Ta2S* fx_result)
{
   fx_copy_str(t0, &fx_result->t0);
   fx_copy_str(t1, &fx_result->t1);
}

_fx_R18Options__options_t _fx_g12Options__opt = {0};
bool _fx_g18Options__is_arch64 =
(bool)(sizeof(void*) > 4)
;
FX_EXTERN_C int _fx_F4reprS1S(fx_str_t*, fx_str_t*, void*);

FX_EXTERN_C int _fx_F12join_embraceS4SSSA1S(fx_str_t*, fx_str_t*, fx_str_t*, fx_arr_t*, fx_str_t*, void*);

FX_EXTERN_C void _fx_F12print_stringv1S(fx_str_t*, void*);

FX_EXTERN_C bool _fx_F6__eq__B2SS(fx_str_t*, fx_str_t*, void*);

FX_EXTERN_C void _fx_M6StringFM7to_int_Nt6option1i2Si(fx_str_t*, int_, struct _fx_Nt6option1i*, void*);

FX_EXTERN_C int_ _fx_M6StringFM10to_int_or_i3Sii(fx_str_t*, int_, int_, void*);

FX_EXTERN_C_VAL(struct _fx_LS_data_t* _fx_g9Sys__argv)
FX_EXTERN_C int _fx_M8FilenameFM8basenameS1S(fx_str_t*, fx_str_t*, void*);

FX_EXTERN_C_VAL(fx_str_t _fx_g21__ficus_version_str__)
FX_EXTERN_C_VAL(fx_str_t _fx_g20__ficus_git_commit__)
FX_EXTERN_C int _fx_M8FilenameFM6getcwdS0(fx_str_t*, void*);

FX_EXTERN_C bool _fx_M6StringFM10startswithB2SS(fx_str_t*, fx_str_t*, void*);

FX_EXTERN_C int_ _fx_M6StringFM4findi2SC(fx_str_t*, char_, void*);

FX_EXTERN_C bool _fx_M4CharFM7isalphaB1C(char_, void*);

FX_EXTERN_C bool _fx_M4CharFM7isalnumB1C(char_, void*);

FX_EXTERN_C bool _fx_M4CharFM7isdigitB1C(char_, void*);

FX_EXTERN_C bool _fx_M6StringFM10startswithB2SC(fx_str_t*, char_, void*);

FX_EXTERN_C bool _fx_M6StringFM8endswithB2SC(fx_str_t*, char_, void*);

FX_EXTERN_C_VAL(struct _fx_FPS1B _fx_g11Sys__osname)
FX_EXTERN_C int _fx_M3SysFM10cc_versionS0(fx_str_t*, void*);

FX_EXTERN_C int _fx_M8FilenameFM9normalizeS2SS(fx_str_t*, fx_str_t*, fx_str_t*, void*);

FX_EXTERN_C int _fx_M8FilenameFM16remove_extensionS1S(fx_str_t*, fx_str_t*, void*);

FX_EXTERN_C void _fx_M7OptionsFM5link2LS2LSLS(
   struct _fx_LS_data_t* l1,
   struct _fx_LS_data_t* l2,
   struct _fx_LS_data_t** fx_result,
   void* fx_fv)
{

fx_link_lists(l1, l2, fx_result);

}

FX_EXTERN_C int _fx_M7OptionsFM7__add__LS2LSLS(
   struct _fx_LS_data_t* l1_0,
   struct _fx_LS_data_t* l2_0,
   struct _fx_LS_data_t** fx_result,
   void* fx_fv)
{
   int fx_status = 0;
   if (l1_0 == 0) {
      FX_COPY_PTR(l2_0, fx_result);
   }
   else if (l2_0 == 0) {
      FX_COPY_PTR(l1_0, fx_result);
   }
   else {
      _fx_LS v_0 = 0;
      _fx_LS lstend_0 = 0;
      _fx_LS lst_0 = l1_0;
      for (; lst_0; lst_0 = lst_0->tl) {
         fx_str_t* x_0 = &lst_0->hd;
         _fx_LS node_0 = 0;
         FX_CALL(_fx_cons_LS(x_0, 0, false, &node_0), _fx_catch_0);
         FX_LIST_APPEND(v_0, lstend_0, node_0);

      _fx_catch_0: ;
         FX_CHECK_EXN(_fx_catch_1);
      }
      _fx_M7OptionsFM5link2LS2LSLS(v_0, l2_0, fx_result, 0);

   _fx_catch_1: ;
      if (v_0) {
         _fx_free_LS(&v_0);
      }
   }
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM6stringS1S(fx_str_t* a_0, fx_str_t* fx_result, void* fx_fv)
{
   int fx_status = 0;
   fx_copy_str(a_0, fx_result);
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM6stringS1LS(struct _fx_LS_data_t* l_0, fx_str_t* fx_result, void* fx_fv)
{
   fx_arr_t v_0 = {0};
   int fx_status = 0;
   fx_str_t* dstptr_0 = 0;
   _fx_LS lst_0 = l_0;
   int_ len_0 = fx_list_length(lst_0);
   {
      const int_ shape_0[] = { len_0 };
      FX_CALL(fx_make_arr(1, shape_0, sizeof(fx_str_t), (fx_free_t)fx_free_str, (fx_copy_t)fx_copy_str, 0, &v_0), _fx_cleanup);
   }
   dstptr_0 = (fx_str_t*)v_0.data;
   for (; lst_0; lst_0 = lst_0->tl, dstptr_0++) {
      fx_str_t res_0 = {0};
      fx_str_t* x_0 = &lst_0->hd;
      FX_CALL(_fx_F4reprS1S(x_0, &res_0, 0), _fx_catch_0);
      fx_copy_str(&res_0, dstptr_0);

   _fx_catch_0: ;
      FX_FREE_STR(&res_0);
      FX_CHECK_EXN(_fx_cleanup);
   }
   fx_str_t slit_0 = FX_MAKE_STR("[");
   fx_str_t slit_1 = FX_MAKE_STR("]");
   fx_str_t slit_2 = FX_MAKE_STR(", ");
   FX_CALL(_fx_F12join_embraceS4SSSA1S(&slit_0, &slit_1, &slit_2, &v_0, fx_result, 0), _fx_cleanup);

_fx_cleanup: ;
   FX_FREE_ARR(&v_0);
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM3maxi2ii(int_ a_0, int_ b_0, int_* fx_result, void* fx_fv)
{
   int fx_status = 0;
   *fx_result = fx_maxi(a_0, b_0);
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM7printlnv1S(fx_str_t* a_0, void* fx_fv)
{
   int fx_status = 0;
   _fx_F12print_stringv1S(a_0, 0);
   fx_str_t slit_0 = FX_MAKE_STR("\n");
   _fx_F12print_stringv1S(&slit_0, 0);
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM2tlLS1LS(struct _fx_LS_data_t* __pat___0, struct _fx_LS_data_t** fx_result, void* fx_fv)
{
   int fx_status = 0;
   if (__pat___0 != 0) {
      FX_COPY_PTR(__pat___0->tl, fx_result);
   }
   else {
      FX_FAST_THROW(FX_EXN_NullListError, _fx_cleanup);
   }

_fx_cleanup: ;
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM3memB2LSS(struct _fx_LS_data_t* l_0, fx_str_t* a_0, bool* fx_result, void* fx_fv)
{
   int fx_status = 0;
   bool __fold_result___0 = false;
   _fx_LS lst_0 = l_0;
   for (; lst_0; lst_0 = lst_0->tl) {
      fx_str_t* b_0 = &lst_0->hd;
      bool v_0 = _fx_F6__eq__B2SS(a_0, b_0, 0);
      if (v_0) {
         __fold_result___0 = true; FX_BREAK(_fx_catch_0);
      }

   _fx_catch_0: ;
      FX_CHECK_BREAK();
      FX_CHECK_EXN(_fx_cleanup);
   }
   *fx_result = __fold_result___0;

_fx_cleanup: ;
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM6lengthi1S(fx_str_t* s_0, int_* fx_result, void* fx_fv)
{
   int fx_status = 0;
   *fx_result = FX_STR_LENGTH(*s_0);
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM6to_intNt6option1i2Si(fx_str_t* a_0, int_ base_0, struct _fx_Nt6option1i* fx_result, void* fx_fv)
{
   int fx_status = 0;
   _fx_M6StringFM7to_int_Nt6option1i2Si(a_0, base_0, fx_result, 0);
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM9to_int_ori3Sii(fx_str_t* a_0, int_ defval_0, int_ base_0, int_* fx_result, void* fx_fv)
{
   int fx_status = 0;
   *fx_result = _fx_M6StringFM10to_int_or_i3Sii(a_0, defval_0, base_0, 0);
   return fx_status;
}

FX_EXTERN_C void _fx_M7OptionsFM7OptBoolN17Options__optval_t1B(bool arg0, struct _fx_N17Options__optval_t* fx_result)
{
   fx_result->tag = 1;
   fx_result->u.OptBool = arg0;
}

FX_EXTERN_C void _fx_M7OptionsFM6OptIntN17Options__optval_t1i(int_ arg0, struct _fx_N17Options__optval_t* fx_result)
{
   fx_result->tag = 2;
   fx_result->u.OptInt = arg0;
}

FX_EXTERN_C void _fx_M7OptionsFM9OptStringN17Options__optval_t1S(fx_str_t* arg0, struct _fx_N17Options__optval_t* fx_result)
{
   fx_result->tag = 3;
   fx_copy_str(arg0, &fx_result->u.OptString);
}

FX_EXTERN_C int _fx_M7OptionsFM15default_optionsRM9options_t0(struct _fx_R18Options__options_t* fx_result, void* fx_fv)
{
   int fx_status = 0;
   fx_str_t slit_0 = FX_MAKE_STR("");
   fx_str_t slit_1 = FX_MAKE_STR("");
   fx_str_t slit_2 = FX_MAKE_STR("");
   fx_str_t slit_3 = FX_MAKE_STR("");
   fx_str_t slit_4 = FX_MAKE_STR("");
   fx_str_t slit_5 = FX_MAKE_STR("");
   fx_str_t slit_6 = FX_MAKE_STR("");
   fx_str_t slit_7 = FX_MAKE_STR("human");
   _fx_make_R18Options__options_t(0, &slit_0, true, false, &slit_1, &slit_2, &slit_3, &slit_4, false, &slit_5, true, 0, false,
      0, 0, 100, true, false, true, true, 1, &slit_6, false, false, false, false, false, false, false, false, true, false,
      false, false, 100, &slit_7, fx_result);
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM18force_full_rebuildv0(void* fx_fv)
{
   int fx_status = 0;
   bool* v_0 = &_fx_g12Options__opt.force_rebuild;
   *v_0 = true;
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM10print_helpv1B(bool detailed_0, void* fx_fv)
{
   fx_str_t v_0 = {0};
   fx_str_t fxname_0 = {0};
   fx_str_t v_1 = {0};
   fx_str_t v_2 = {0};
   fx_str_t v_3 = {0};
   int fx_status = 0;
   if (_fx_g9Sys__argv != 0) {
      fx_copy_str(&_fx_g9Sys__argv->hd, &v_0);
   }
   else {
      FX_FAST_THROW(FX_EXN_NullListError, _fx_cleanup);
   }
   FX_CHECK_EXN(_fx_cleanup);
   FX_CALL(_fx_M8FilenameFM8basenameS1S(&v_0, &fxname_0, 0), _fx_cleanup);
   fx_str_t slit_0 = FX_MAKE_STR("Ficus compiler v");
   fx_str_t slit_1 = FX_MAKE_STR(" (git ");
   fx_str_t slit_2 = FX_MAKE_STR(")");
   {
      const fx_str_t strs_0[] = { slit_0, _fx_g21__ficus_version_str__, slit_1, _fx_g20__ficus_git_commit__, slit_2 };
      FX_CALL(fx_strjoin(0, 0, 0, strs_0, 5, &v_1), _fx_cleanup);
   }
   _fx_F12print_stringv1S(&v_1, 0);
   fx_str_t slit_3 = FX_MAKE_STR("\n");
   _fx_F12print_stringv1S(&slit_3, 0);
   if (!detailed_0) {
      fx_str_t slit_4 =
         FX_MAKE_STR("\n"
            U"Usage: ");
      fx_str_t slit_5 =
         FX_MAKE_STR(" [-pr-tokens | -pr-ast0 | -pr-ast | -pr-k0 | -pr-k | -no-c\n"
            U"    | -app | -run | -O0 | -O1 | -O3 | -inline-threshold <n> | -no-openmp\n"
            U"    | -o <output_name> | -I <incdir> | -B <build_root>\n"
            U"    | -c++ | -cflags <cflags> | -clibs <clibs>\n"
            U"    | -verbose | -h | -v ] <input_file>.fx [-- <app_args ...>]\n"
            U"\n"
            U"Run \'");
      fx_str_t slit_6 = FX_MAKE_STR(" -h\' to get more detailed help");
      {
         const fx_str_t strs_1[] = { slit_4, fxname_0, slit_5, fxname_0, slit_6 };
         FX_CALL(fx_strjoin(0, 0, 0, strs_1, 5, &v_2), _fx_cleanup);
      }
      _fx_F12print_stringv1S(&v_2, 0);
      fx_str_t slit_7 = FX_MAKE_STR("\n");
      _fx_F12print_stringv1S(&slit_7, 0);
   }
   else {
      fx_str_t slit_8 =
         FX_MAKE_STR("\n"
            U"Usage: ");
      fx_str_t slit_9 =
         FX_MAKE_STR(" [options ...] <input_file.fx> [-- <app_args ...>]\n"
            U"\n"
            U"where options can be some of:\n"
            U"    -rebuild        Ignore cached files; rebuild everything from scratch\n"
            U"    -pr-tokens      Print all the tokens in parsed files\n"
            U"    -pr-ast0        Print AST right after parsing\n"
            U"    -pr-ast         Print typechecked AST of the parsed files\n"
            U"    -pr-k0          Print just generated K-form\n"
            U"    -pr-k           Print optimized K-form of the parsed files\n"
            U"                    (only a part of the generated K-form is retained\n"
            U"                    because of the dead code elimination step)\n"
            U"    -pr-resolve     Trace overload resolution: for every call whose viable\n"
            U"                    candidate set has >1 entry, print the candidates, the\n"
            U"                    env-order winner (current behavior) and the generality\n"
            U"                    winner (WP-E). Diagnostic only; does not change resolution.\n"
            U"    -no-c           Do not generate C code\n"
            U"    -app            Build application (default mode)\n"
            U"    -run            Build application and run it\n"
            U"    -O0             Optimization level 0: disable all optimizations\n"
            U"                                         except for the most essential ones\n"
            U"    -O1             Optimization level 1 (default): enable most of the optimizations\n"
            U"    -O3             Optimization level 3: enable all optimizations\n"
            U"    -Ofast          Optimization level 3; passes \'-Ofast\' to C/C++ compiler\n"
            U"    -no-openmp      Disable OpenMP (OpenMP is enabled by default)\n"
            U"    -debug          Turn on debug information, disable optimizations\n"
            U"                    (but it can be overwritten with further -On)\n"
            U"    -optim-iters    The number of optimization iterations to perform (2 or 3 by default, depending on -O<n>)\n"
            U"    -inline-threshold  Inline threshold (100 by default); the higher it is,\n"
            U"                    the bigger functions are inlined;\n"
            U"                    --inline-thresh=0 disables inline expansion\n"
            U"    -relax          Do not require explicit typing of all global functions\' parameters\n"
            U"    -no-preamble    Do not auto-import \'Builtins\', \'List\', \'String\' and\n"
            U"                    a few other standard modules into each compiled module.\n"
            U"    -Wno-unused     Do not report errors about unused values/functions\n"
            U"    -Wimplicit-rettype  Warn about every module-level function whose return\n"
            U"                    type is left to inference; the message prints the inferred\n"
            U"                    type so the fix is copy-paste. Nested functions and lambdas\n"
            U"                    are exempt. By default covers all USER modules (everything\n"
            U"                    outside the stdlib) so a multi-file project is fully\n"
            U"                    checked, not just the file named on the command line.\n"
            U"    -Wimplicit-rettype=all  As above, but ALSO check the stdlib modules\n"
            U"                    (used to gate the stdlib itself; normally you do not want\n"
            U"                    warnings about library code you did not write).\n"
            U"    -Wall           Enable all recommended warnings (currently just\n"
            U"                    -Wimplicit-rettype)\n"
            U"    -Werror         Treat all emitted warnings as errors: exit with a nonzero\n"
            U"                    status if any warning was generated\n"
            U"    -fmax-errors=N  Print at most N distinct type diagnostics per run (default\n"
            U"                    100); the rest are summarized as \'further diagnostics\n"
            U"                    suppressed\'. The type checker recovers from an error and\n"
            U"                    keeps going, so one run reports many independent problems.\n"
            U"    -diag-format=FMT Diagnostic output format: \'human\' (default, caret text) or\n"
            U"                    \'json\' (one JSON object per diagnostic, jsonl on stdout, for\n"
            U"                    a language server / IDE). Human format is unchanged.\n"
            U"    -o <output_name> Output file name (by default it matches the\n"
            U"                    input filename without .fx extension)\n"
            U"    -D symbol       Define \'symbol=true\' for preprocessor\n"
            U"    -D symbol=value Define \'symbol=value\' for preprocessor.\n"
            U"                    The value may be one of the following:\n"
            U"                      * a boolean: true (or on), false (or off),\n"
            U"                      * an integer (if the value starts with a digit, \'+\' or \'-\' and\n"
            U"                                    contains 1 or more decimal digits)\n"
            U"                      * text string: everything between double quotes or\n"
            U"                                     any combination of characters that does not\n"
            U"                                     contain spaces, \'\' or quotes and does not start with a digit or \'-\'\n"
            U"    -I <dir>        Add specified directory to the module search path\n"
            U"    -B <build_root> Specifies the parent directory <build_root> where subdirectory\n"
            U"                    <build_root>/__fxbuild__/<app_build_dir> with the generated files will be created.\n"
            U"                    By default, <build_root> is the current working directory.\n"
            U"    -c++            Use C++ compiler instead of C to compile the generated sources.\n"
            U"                    \'pragma \"c++\"\' in .fx file also instructs ficus compiler to use C++.\n"
            U"    -cflags <cflags> Pass the specified flags, e.g. \"-mavx2\", to C/C++ compiler.\n"
            U"                    If environment variable FICUS_CFLAGS is set,\n"
            U"                    its value is inserted before <cflags>\n"
            U"    -clibs <clibs>  Pass the specified libs/linker flags to C/C++ compiler.\n"
            U"                    If environment variable FICUS_LINK_LIBRARIES is set,\n"
            U"                    its value is inserted after <clibs>\n"
            U"    -verbose        Display various info during the build\n"
            U"    -h or -help or --help  Display this information\n"
            U"    -v or -version  Display information about compiler and the platform, then exit.\n"
            U"    --              Specify the application parameters when \'-run\' flag is used,\n"
            U"                    e.g. \'./ficus -run myprog.fx -- arg1 arg2\'\n");
      {
         const fx_str_t strs_2[] = { slit_8, fxname_0, slit_9 };
         FX_CALL(fx_strjoin(0, 0, 0, strs_2, 3, &v_3), _fx_cleanup);
      }
      _fx_F12print_stringv1S(&v_3, 0);
      fx_str_t slit_10 = FX_MAKE_STR("\n");
      _fx_F12print_stringv1S(&slit_10, 0);
   }

_fx_cleanup: ;
   FX_FREE_STR(&v_0);
   FX_FREE_STR(&fxname_0);
   FX_FREE_STR(&v_1);
   FX_FREE_STR(&v_2);
   FX_FREE_STR(&v_3);
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM13parse_optionsB0(bool* fx_result, void* fx_fv)
{
   _fx_R18Options__options_t v_0 = {0};
   fx_str_t curr_dir_0 = {0};
   _fx_LS args_0 = 0;
   fx_str_t inputfile_0 = {0};
   _fx_LS v_1 = 0;
   fx_str_t v_2 = {0};
   fx_str_t v_3 = {0};
   fx_str_t v_4 = {0};
   fx_str_t v_5 = {0};
   fx_str_t v_6 = {0};
   fx_str_t v_7 = {0};
   fx_str_t v_8 = {0};
   fx_str_t v_9 = {0};
   fx_str_t v_10 = {0};
   fx_str_t v_11 = {0};
   fx_str_t v_12 = {0};
   fx_str_t v_13 = {0};
   fx_str_t v_14 = {0};
   fx_str_t v_15 = {0};
   fx_str_t v_16 = {0};
   fx_str_t default_output_name_0 = {0};
   fx_str_t default_output_name_1 = {0};
   fx_str_t v_17 = {0};
   fx_str_t v_18 = {0};
   fx_str_t v_19 = {0};
   fx_str_t v_20 = {0};
   fx_str_t v_21 = {0};
   fx_str_t v_22 = {0};
   fx_str_t v_23 = {0};
   fx_str_t v_24 = {0};
   fx_str_t v_25 = {0};
   fx_str_t v_26 = {0};
   fx_str_t v_27 = {0};
   fx_str_t v_28 = {0};
   fx_str_t v_29 = {0};
   fx_str_t v_30 = {0};
   int fx_status = 0;
   FX_CALL(_fx_M7OptionsFM15default_optionsRM9options_t0(&v_0, 0), _fx_cleanup);
   _fx_free_R18Options__options_t(&_fx_g12Options__opt);
   _fx_copy_R18Options__options_t(&v_0, &_fx_g12Options__opt);
   bool* v_31 = &_fx_g12Options__opt.arch64;
   *v_31 = _fx_g18Options__is_arch64;
   FX_CALL(_fx_M8FilenameFM6getcwdS0(&curr_dir_0, 0), _fx_cleanup);
   FX_CALL(_fx_M7OptionsFM2tlLS1LS(_fx_g9Sys__argv, &args_0, 0), _fx_cleanup);
   fx_str_t slit_0 = FX_MAKE_STR("");
   fx_copy_str(&slit_0, &inputfile_0);
   int_ prhelp_0 = 0;
   bool prver_0 = false;
   bool ok_0 = true;
   while (args_0 != 0) {
      _fx_LS args_1 = 0;
      _fx_LS v_32 = 0;
      FX_COPY_PTR(args_0, &args_1);
      if (args_1 != 0) {
         fx_str_t slit_1 = FX_MAKE_STR("-no-preamble");
         if (fx_streq(&args_1->hd, &slit_1)) {
            bool* v_33 = &_fx_g12Options__opt.use_preamble; *v_33 = false; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_2 = FX_MAKE_STR("-rebuild");
         if (fx_streq(&args_1->hd, &slit_2)) {
            bool* v_34 = &_fx_g12Options__opt.force_rebuild; *v_34 = true; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_3 = FX_MAKE_STR("-pr-tokens");
         if (fx_streq(&args_1->hd, &slit_3)) {
            bool* v_35 = &_fx_g12Options__opt.print_tokens; *v_35 = true; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_4 = FX_MAKE_STR("-pr-ast0");
         if (fx_streq(&args_1->hd, &slit_4)) {
            bool* v_36 = &_fx_g12Options__opt.print_ast0; *v_36 = true; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_5 = FX_MAKE_STR("-pr-ast");
         if (fx_streq(&args_1->hd, &slit_5)) {
            bool* v_37 = &_fx_g12Options__opt.print_ast; *v_37 = true; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_6 = FX_MAKE_STR("-pr-k0");
         if (fx_streq(&args_1->hd, &slit_6)) {
            bool* v_38 = &_fx_g12Options__opt.print_k0; *v_38 = true; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_7 = FX_MAKE_STR("-pr-k");
         if (fx_streq(&args_1->hd, &slit_7)) {
            bool* v_39 = &_fx_g12Options__opt.print_k; *v_39 = true; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_8 = FX_MAKE_STR("-pr-resolve");
         if (fx_streq(&args_1->hd, &slit_8)) {
            bool* v_40 = &_fx_g12Options__opt.print_resolve; *v_40 = true; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_9 = FX_MAKE_STR("-no-c");
         if (fx_streq(&args_1->hd, &slit_9)) {
            bool* v_41 = &_fx_g12Options__opt.gen_c; *v_41 = false; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_10 = FX_MAKE_STR("-app");
         if (fx_streq(&args_1->hd, &slit_10)) {
            bool* v_42 = &_fx_g12Options__opt.make_app; *v_42 = true; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_11 = FX_MAKE_STR("-run");
         if (fx_streq(&args_1->hd, &slit_11)) {
            bool* v_43 = &_fx_g12Options__opt.run_app; *v_43 = true; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_12 = FX_MAKE_STR("-O0");
         if (fx_streq(&args_1->hd, &slit_12)) {
            int_* v_44 = &_fx_g12Options__opt.optimize_level; *v_44 = 0; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_13 = FX_MAKE_STR("-O1");
         if (fx_streq(&args_1->hd, &slit_13)) {
            int_* v_45 = &_fx_g12Options__opt.optimize_level; *v_45 = 1; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_14 = FX_MAKE_STR("-O3");
         if (fx_streq(&args_1->hd, &slit_14)) {
            int_* v_46 = &_fx_g12Options__opt.optimize_level; *v_46 = 3; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_15 = FX_MAKE_STR("-Ofast");
         if (fx_streq(&args_1->hd, &slit_15)) {
            int_* v_47 = &_fx_g12Options__opt.optimize_level; *v_47 = 100; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_16 = FX_MAKE_STR("-no-openmp");
         if (fx_streq(&args_1->hd, &slit_16)) {
            bool* v_48 = &_fx_g12Options__opt.enable_openmp; *v_48 = false; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_17 = FX_MAKE_STR("-debug");
         if (fx_streq(&args_1->hd, &slit_17)) {
            bool* v_49 = &_fx_g12Options__opt.debug; *v_49 = true; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_18 = FX_MAKE_STR("-optim-iters");
         if (fx_streq(&args_1->hd, &slit_18)) {
            _fx_LS v_50 = args_1->tl;
            if (v_50 != 0) {
               fx_str_t v_51 = {0};
               fx_str_t v_52 = {0};
               int_ i_0;
               FX_CALL(_fx_M7OptionsFM9to_int_ori3Sii(&v_50->hd, -1, 0, &i_0, 0), _fx_catch_0);
               if (i_0 >= 0) {
                  int_* v_53 = &_fx_g12Options__opt.optim_iters; *v_53 = i_0; FX_COPY_PTR(v_50->tl, &v_32);
               }
               else {
                  fx_str_t slit_19 = FX_MAKE_STR("[31;1merror:[0m");
                  FX_CALL(_fx_M7OptionsFM6stringS1S(&slit_19, &v_51, 0), _fx_catch_0);
                  fx_str_t slit_20 = FX_MAKE_STR(" invalid -optim-iters argument; must be a non-negative integer");
                  {
                     const fx_str_t strs_0[] = { v_51, slit_20 };
                     FX_CALL(fx_strjoin(0, 0, 0, strs_0, 2, &v_52), _fx_catch_0);
                  }
                  FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_52, 0), _fx_catch_0);
                  ok_0 = false;
               }

            _fx_catch_0: ;
               FX_FREE_STR(&v_52);
               FX_FREE_STR(&v_51);
               goto _fx_endmatch_3;
            }
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_21 = FX_MAKE_STR("-inline-threshold");
         if (fx_streq(&args_1->hd, &slit_21)) {
            _fx_LS v_54 = args_1->tl;
            if (v_54 != 0) {
               fx_str_t v_55 = {0};
               fx_str_t v_56 = {0};
               int_ i_1;
               FX_CALL(_fx_M7OptionsFM9to_int_ori3Sii(&v_54->hd, -1, 0, &i_1, 0), _fx_catch_1);
               if (i_1 >= 0) {
                  int_* v_57 = &_fx_g12Options__opt.optim_iters; *v_57 = i_1; FX_COPY_PTR(v_54->tl, &v_32);
               }
               else {
                  fx_str_t slit_22 = FX_MAKE_STR("[31;1merror:[0m");
                  FX_CALL(_fx_M7OptionsFM6stringS1S(&slit_22, &v_55, 0), _fx_catch_1);
                  fx_str_t slit_23 = FX_MAKE_STR(" invalid -inline-threshold argument; must be a non-negative integer");
                  {
                     const fx_str_t strs_1[] = { v_55, slit_23 };
                     FX_CALL(fx_strjoin(0, 0, 0, strs_1, 2, &v_56), _fx_catch_1);
                  }
                  FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_56, 0), _fx_catch_1);
                  ok_0 = false;
               }

            _fx_catch_1: ;
               FX_FREE_STR(&v_56);
               FX_FREE_STR(&v_55);
               goto _fx_endmatch_3;
            }
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_24 = FX_MAKE_STR("-relax");
         if (fx_streq(&args_1->hd, &slit_24)) {
            bool* v_58 = &_fx_g12Options__opt.relax; *v_58 = true; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_25 = FX_MAKE_STR("-Wno-unused");
         if (fx_streq(&args_1->hd, &slit_25)) {
            bool* v_59 = &_fx_g12Options__opt.W_unused; *v_59 = false; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_26 = FX_MAKE_STR("-Wimplicit-rettype");
         if (fx_streq(&args_1->hd, &slit_26)) {
            bool* v_60 = &_fx_g12Options__opt.W_implicit_rettype;
            *v_60 = true;
            FX_COPY_PTR(args_1->tl, &v_32);
            goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_27 = FX_MAKE_STR("-Wimplicit-rettype=all");
         if (fx_streq(&args_1->hd, &slit_27)) {
            bool* v_61 = &_fx_g12Options__opt.W_implicit_rettype;
            *v_61 = true;
            bool* v_62 = &_fx_g12Options__opt.W_implicit_rettype_all;
            *v_62 = true;
            FX_COPY_PTR(args_1->tl, &v_32);
            goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_28 = FX_MAKE_STR("-Wall");
         if (fx_streq(&args_1->hd, &slit_28)) {
            bool* v_63 = &_fx_g12Options__opt.W_implicit_rettype;
            *v_63 = true;
            FX_COPY_PTR(args_1->tl, &v_32);
            goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_29 = FX_MAKE_STR("-Werror");
         if (fx_streq(&args_1->hd, &slit_29)) {
            bool* v_64 = &_fx_g12Options__opt.Werror; *v_64 = true; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t* opt_str_0 = &args_1->hd;
         fx_str_t slit_30 = FX_MAKE_STR("-fmax-errors=");
         if (_fx_M6StringFM10startswithB2SS(opt_str_0, &slit_30, 0)) {
            fx_str_t vstr_0 = {0};
            fx_str_t slit_31 = FX_MAKE_STR("-fmax-errors=");
            int_ res_0;
            FX_CALL(_fx_M7OptionsFM6lengthi1S(&slit_31, &res_0, 0), _fx_catch_3);
            FX_CALL(fx_substr(opt_str_0, res_0, 0, 1, 2, &vstr_0), _fx_catch_3);
            _fx_Nt6option1i v_65;
            FX_CALL(_fx_M7OptionsFM6to_intNt6option1i2Si(&vstr_0, 0, &v_65, 0), _fx_catch_3);
            if (v_65.tag == 2) {
               int_ n_0 = v_65.u.Some;
               if (n_0 > 0) {
                  int_* v_66 = &_fx_g12Options__opt.max_errors; *v_66 = n_0; goto _fx_endmatch_0;
               }
            }
            fx_str_t v_67 = {0};
            fx_str_t v_68 = {0};
            FX_CALL(_fx_M7OptionsFM6stringS1S(&vstr_0, &v_67, 0), _fx_catch_2);
            fx_str_t slit_32 = FX_MAKE_STR("invalid -fmax-errors value \'");
            fx_str_t slit_33 = FX_MAKE_STR("\' (expected a positive integer)");
            {
               const fx_str_t strs_2[] = { slit_32, v_67, slit_33 };
               FX_CALL(fx_strjoin(0, 0, 0, strs_2, 3, &v_68), _fx_catch_2);
            }
            FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_68, 0), _fx_catch_2);
            ok_0 = false;

         _fx_catch_2: ;
            FX_FREE_STR(&v_68);
            FX_FREE_STR(&v_67);

         _fx_endmatch_0: ;
            FX_CHECK_EXN(_fx_catch_3);
            FX_COPY_PTR(args_1->tl, &v_32);

         _fx_catch_3: ;
            FX_FREE_STR(&vstr_0);
            goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t* opt_str_1 = &args_1->hd;
         fx_str_t slit_34 = FX_MAKE_STR("-diag-format=");
         if (_fx_M6StringFM10startswithB2SS(opt_str_1, &slit_34, 0)) {
            fx_str_t vstr_1 = {0};
            fx_str_t v_69 = {0};
            fx_str_t v_70 = {0};
            fx_str_t slit_35 = FX_MAKE_STR("-diag-format=");
            int_ res_1;
            FX_CALL(_fx_M7OptionsFM6lengthi1S(&slit_35, &res_1, 0), _fx_catch_4);
            FX_CALL(fx_substr(opt_str_1, res_1, 0, 1, 2, &vstr_1), _fx_catch_4);
            bool v_71;
            fx_str_t slit_36 = FX_MAKE_STR("human");
            if (_fx_F6__eq__B2SS(&vstr_1, &slit_36, 0)) {
               v_71 = true;
            }
            else {
               fx_str_t slit_37 = FX_MAKE_STR("json"); v_71 = _fx_F6__eq__B2SS(&vstr_1, &slit_37, 0);
            }
            if (v_71) {
               fx_str_t* v_72 = &_fx_g12Options__opt.diag_format; FX_FREE_STR(v_72); fx_copy_str(&vstr_1, v_72);
            }
            else {
               FX_CALL(_fx_M7OptionsFM6stringS1S(&vstr_1, &v_69, 0), _fx_catch_4);
               fx_str_t slit_38 = FX_MAKE_STR("invalid -diag-format value \'");
               fx_str_t slit_39 = FX_MAKE_STR("\' (expected \'human\' or \'json\')");
               {
                  const fx_str_t strs_3[] = { slit_38, v_69, slit_39 };
                  FX_CALL(fx_strjoin(0, 0, 0, strs_3, 3, &v_70), _fx_catch_4);
               }
               FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_70, 0), _fx_catch_4);
               ok_0 = false;
            }
            FX_COPY_PTR(args_1->tl, &v_32);

         _fx_catch_4: ;
            FX_FREE_STR(&v_70);
            FX_FREE_STR(&v_69);
            FX_FREE_STR(&vstr_1);
            goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_40 = FX_MAKE_STR("-verbose");
         if (fx_streq(&args_1->hd, &slit_40)) {
            bool* v_73 = &_fx_g12Options__opt.verbose; *v_73 = true; FX_COPY_PTR(args_1->tl, &v_32); goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_41 = FX_MAKE_STR("-o");
         if (fx_streq(&args_1->hd, &slit_41)) {
            _fx_LS v_74 = args_1->tl;
            if (v_74 != 0) {
               fx_str_t* v_75 = &_fx_g12Options__opt.output_name;
               fx_str_t* oname_0 = &v_74->hd;
               FX_FREE_STR(v_75);
               fx_copy_str(oname_0, v_75);
               FX_COPY_PTR(v_74->tl, &v_32);
               goto _fx_endmatch_3;
            }
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_42 = FX_MAKE_STR("-D");
         if (fx_streq(&args_1->hd, &slit_42)) {
            _fx_LS v_76 = args_1->tl;
            if (v_76 != 0) {
               _fx_Ta2S v_77 = {0};
               fx_str_t v_78 = {0};
               fx_str_t v_79 = {0};
               fx_str_t name_0 = {0};
               fx_str_t value_0 = {0};
               _fx_N17Options__optval_t errval_0 = {0};
               _fx_N17Options__optval_t value_1 = {0};
               fx_str_t v_80 = {0};
               fx_str_t v_81 = {0};
               fx_str_t v_82 = {0};
               fx_str_t v_83 = {0};
               fx_str_t v_84 = {0};
               fx_str_t v_85 = {0};
               fx_str_t v_86 = {0};
               _fx_T2SN17Options__optval_t v_87 = {0};
               _fx_LT2SN17Options__optval_t v_88 = 0;
               _fx_LT2SN17Options__optval_t v_89 = 0;
               fx_str_t* nameval_0 = &v_76->hd;
               int_ p1_0 = _fx_M6StringFM4findi2SC(nameval_0, (char_)61, 0);
               if (p1_0 < 0) {
                  fx_str_t slit_43 = FX_MAKE_STR("true"); _fx_make_Ta2S(nameval_0, &slit_43, &v_77);
               }
               else {
                  FX_CALL(fx_substr(nameval_0, 0, p1_0, 1, 1, &v_78), _fx_catch_7);
                  FX_CALL(fx_substr(nameval_0, p1_0 + 1, 0, 1, 2, &v_79), _fx_catch_7);
                  _fx_make_Ta2S(&v_78, &v_79, &v_77);
               }
               fx_copy_str(&v_77.t0, &name_0);
               fx_copy_str(&v_77.t1, &value_0);
               _fx_M7OptionsFM7OptBoolN17Options__optval_t1B(false, &errval_0);
               bool v_90;
               bool t_0;
               if (FX_STR_LENGTH(name_0) != 0) {
                  FX_STR_CHKIDX(name_0, 0, _fx_catch_7);
                  char_ v_91 = FX_STR_ELEM(name_0, 0);
                  if (_fx_M4CharFM7isalphaB1C(v_91, 0)) {
                     t_0 = true;
                  }
                  else {
                     FX_STR_CHKIDX(name_0, 0, _fx_catch_7); char_ v_92 = FX_STR_ELEM(name_0, 0); t_0 = v_92 == (char_)95;
                  }
               }
               else {
                  t_0 = false;
               }
               if (t_0) {
                  bool __fold_result___0 = true;
                  int_ len_0 = FX_STR_LENGTH(name_0);
                  for (int_ i_2 = 0; i_2 < len_0; i_2++) {
                     char_ c_0 = name_0.data[i_2];
                     bool v_93;
                     if (_fx_M4CharFM7isalnumB1C(c_0, 0)) {
                        v_93 = true;
                     }
                     else {
                        v_93 = c_0 == (char_)95;
                     }
                     if (!v_93) {
                        __fold_result___0 = false; FX_BREAK(_fx_catch_5);
                     }

                  _fx_catch_5: ;
                     FX_CHECK_BREAK();
                     FX_CHECK_EXN(_fx_catch_7);
                  }
                  v_90 = __fold_result___0;
               }
               else {
                  v_90 = false;
               }
               if (v_90) {
                  bool v_94;
                  fx_str_t slit_44 = FX_MAKE_STR("TRUE");
                  bool t_1;
                  if (_fx_F6__eq__B2SS(&value_0, &slit_44, 0)) {
                     t_1 = true;
                  }
                  else {
                     fx_str_t slit_45 = FX_MAKE_STR("true"); t_1 = _fx_F6__eq__B2SS(&value_0, &slit_45, 0);
                  }
                  bool t_2;
                  if (t_1) {
                     t_2 = true;
                  }
                  else {
                     fx_str_t slit_46 = FX_MAKE_STR("ON"); t_2 = _fx_F6__eq__B2SS(&value_0, &slit_46, 0);
                  }
                  if (t_2) {
                     v_94 = true;
                  }
                  else {
                     fx_str_t slit_47 = FX_MAKE_STR("on"); v_94 = _fx_F6__eq__B2SS(&value_0, &slit_47, 0);
                  }
                  if (v_94) {
                     _fx_M7OptionsFM7OptBoolN17Options__optval_t1B(true, &value_1);
                  }
                  else {
                     bool v_95;
                     fx_str_t slit_48 = FX_MAKE_STR("FALSE");
                     bool t_3;
                     if (_fx_F6__eq__B2SS(&value_0, &slit_48, 0)) {
                        t_3 = true;
                     }
                     else {
                        fx_str_t slit_49 = FX_MAKE_STR("false"); t_3 = _fx_F6__eq__B2SS(&value_0, &slit_49, 0);
                     }
                     bool t_4;
                     if (t_3) {
                        t_4 = true;
                     }
                     else {
                        fx_str_t slit_50 = FX_MAKE_STR("OFF"); t_4 = _fx_F6__eq__B2SS(&value_0, &slit_50, 0);
                     }
                     if (t_4) {
                        v_95 = true;
                     }
                     else {
                        fx_str_t slit_51 = FX_MAKE_STR("off"); v_95 = _fx_F6__eq__B2SS(&value_0, &slit_51, 0);
                     }
                     if (v_95) {
                        _fx_M7OptionsFM7OptBoolN17Options__optval_t1B(false, &value_1);
                     }
                     else if (FX_STR_LENGTH(value_0) == 0) {
                        FX_CALL(_fx_M7OptionsFM6stringS1S(&name_0, &v_80, 0), _fx_catch_7);
                        fx_str_t slit_52 = FX_MAKE_STR("a value should follow after \'");
                        fx_str_t slit_53 = FX_MAKE_STR("=\'");
                        {
                           const fx_str_t strs_4[] = { slit_52, v_80, slit_53 };
                           FX_CALL(fx_strjoin(0, 0, 0, strs_4, 3, &v_81), _fx_catch_7);
                        }
                        FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_81, 0), _fx_catch_7);
                        ok_0 = false;
                        _fx_copy_N17Options__optval_t(&errval_0, &value_1);
                     }
                     else {
                        FX_STR_CHKIDX(value_0, 0, _fx_catch_7);
                        char_ v_96 = FX_STR_ELEM(value_0, 0);
                        bool v_97;
                        bool t_5;
                        if (v_96 == (char_)43) {
                           t_5 = true;
                        }
                        else {
                           FX_STR_CHKIDX(value_0, 0, _fx_catch_7);
                           char_ v_98 = FX_STR_ELEM(value_0, 0);
                           t_5 = v_98 == (char_)45;
                        }
                        if (t_5) {
                           v_97 = true;
                        }
                        else {
                           FX_STR_CHKIDX(value_0, 0, _fx_catch_7);
                           char_ v_99 = FX_STR_ELEM(value_0, 0);
                           v_97 = _fx_M4CharFM7isdigitB1C(v_99, 0);
                        }
                        if (v_97) {
                           _fx_Nt6option1i v_100;
                           FX_CALL(_fx_M7OptionsFM6to_intNt6option1i2Si(&value_0, 0, &v_100, 0), _fx_catch_7);
                           if (v_100.tag == 2) {
                              _fx_M7OptionsFM6OptIntN17Options__optval_t1i(v_100.u.Some, &value_1);
                           }
                           else {
                              fx_str_t v_101 = {0};
                              fx_str_t v_102 = {0};
                              fx_str_t v_103 = {0};
                              FX_CALL(_fx_M7OptionsFM6stringS1S(&value_0, &v_101, 0), _fx_catch_6);
                              FX_CALL(_fx_M7OptionsFM6stringS1S(&name_0, &v_102, 0), _fx_catch_6);
                              fx_str_t slit_54 = FX_MAKE_STR("invalid numerical value \'");
                              fx_str_t slit_55 = FX_MAKE_STR("\' of a symbol \'");
                              fx_str_t slit_56 = FX_MAKE_STR("\'; if you meant a string, enclose it in double quotes");
                              {
                                 const fx_str_t strs_5[] = { slit_54, v_101, slit_55, v_102, slit_56 };
                                 FX_CALL(fx_strjoin(0, 0, 0, strs_5, 5, &v_103), _fx_catch_6);
                              }
                              FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_103, 0), _fx_catch_6);
                              ok_0 = false;
                              _fx_copy_N17Options__optval_t(&errval_0, &value_1);

                           _fx_catch_6: ;
                              FX_FREE_STR(&v_103);
                              FX_FREE_STR(&v_102);
                              FX_FREE_STR(&v_101);
                           }
                           FX_CHECK_EXN(_fx_catch_7);
                        }
                        else {
                           bool v_104 = _fx_M6StringFM10startswithB2SC(&value_0, (char_)34, 0);
                           if (v_104) {
                              bool v_105 = _fx_M6StringFM8endswithB2SC(&value_0, (char_)34, 0);
                              if (!v_105) {
                                 FX_CALL(_fx_M7OptionsFM6stringS1S(&value_0, &v_82, 0), _fx_catch_7);
                                 fx_str_t slit_57 = FX_MAKE_STR("the value ");
                                 fx_str_t slit_58 = FX_MAKE_STR(" starts with \'\"\', but does not terminate with \'\"\'");
                                 {
                                    const fx_str_t strs_6[] = { slit_57, v_82, slit_58 };
                                    FX_CALL(fx_strjoin(0, 0, 0, strs_6, 3, &v_83), _fx_catch_7);
                                 }
                                 FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_83, 0), _fx_catch_7);
                                 ok_0 = false;
                                 _fx_copy_N17Options__optval_t(&errval_0, &value_1);
                              }
                              else {
                                 FX_CALL(fx_substr(&value_0, 1, -1, 1, 0, &v_84), _fx_catch_7);
                                 _fx_M7OptionsFM9OptStringN17Options__optval_t1S(&v_84, &value_1);
                              }
                           }
                           else {
                              _fx_M7OptionsFM9OptStringN17Options__optval_t1S(&value_0, &value_1);
                           }
                        }
                     }
                  }
               }
               else {
                  FX_CALL(_fx_M7OptionsFM6stringS1S(&name_0, &v_85, 0), _fx_catch_7);
                  fx_str_t slit_59 = FX_MAKE_STR("identifier \'");
                  fx_str_t slit_60 = FX_MAKE_STR("\' contains incorrect characters");
                  {
                     const fx_str_t strs_7[] = { slit_59, v_85, slit_60 };
                     FX_CALL(fx_strjoin(0, 0, 0, strs_7, 3, &v_86), _fx_catch_7);
                  }
                  FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_86, 0), _fx_catch_7);
                  ok_0 = false;
                  _fx_copy_N17Options__optval_t(&errval_0, &value_1);
               }
               if (ok_0) {
                  _fx_make_T2SN17Options__optval_t(&name_0, &value_1, &v_87);
                  FX_COPY_PTR(_fx_g12Options__opt.defines, &v_88);
                  FX_CALL(_fx_cons_LT2SN17Options__optval_t(&v_87, v_88, true, &v_89), _fx_catch_7);
                  _fx_LT2SN17Options__optval_t* v_106 = &_fx_g12Options__opt.defines;
                  _fx_free_LT2SN17Options__optval_t(v_106);
                  FX_COPY_PTR(v_89, v_106);
                  FX_COPY_PTR(v_76->tl, &v_32);
               }

            _fx_catch_7: ;
               if (v_89) {
                  _fx_free_LT2SN17Options__optval_t(&v_89);
               }
               if (v_88) {
                  _fx_free_LT2SN17Options__optval_t(&v_88);
               }
               _fx_free_T2SN17Options__optval_t(&v_87);
               FX_FREE_STR(&v_86);
               FX_FREE_STR(&v_85);
               FX_FREE_STR(&v_84);
               FX_FREE_STR(&v_83);
               FX_FREE_STR(&v_82);
               FX_FREE_STR(&v_81);
               FX_FREE_STR(&v_80);
               _fx_free_N17Options__optval_t(&value_1);
               _fx_free_N17Options__optval_t(&errval_0);
               FX_FREE_STR(&value_0);
               FX_FREE_STR(&name_0);
               FX_FREE_STR(&v_79);
               FX_FREE_STR(&v_78);
               _fx_free_Ta2S(&v_77);
               goto _fx_endmatch_3;
            }
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_61 = FX_MAKE_STR("-I");
         if (fx_streq(&args_1->hd, &slit_61)) {
            _fx_LS v_107 = args_1->tl;
            if (v_107 != 0) {
               _fx_LS v_108 = 0;
               _fx_LS v_109 = 0;
               _fx_LS v_110 = 0;
               FX_COPY_PTR(_fx_g12Options__opt.include_path, &v_108);
               FX_CALL(_fx_cons_LS(&v_107->hd, 0, true, &v_109), _fx_catch_8);
               FX_CALL(_fx_M7OptionsFM7__add__LS2LSLS(v_108, v_109, &v_110, 0), _fx_catch_8);
               _fx_LS* v_111 = &_fx_g12Options__opt.include_path;
               _fx_free_LS(v_111);
               FX_COPY_PTR(v_110, v_111);
               FX_COPY_PTR(v_107->tl, &v_32);

            _fx_catch_8: ;
               if (v_110) {
                  _fx_free_LS(&v_110);
               }
               if (v_109) {
                  _fx_free_LS(&v_109);
               }
               if (v_108) {
                  _fx_free_LS(&v_108);
               }
               goto _fx_endmatch_3;
            }
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_62 = FX_MAKE_STR("-B");
         if (fx_streq(&args_1->hd, &slit_62)) {
            _fx_LS v_112 = args_1->tl;
            if (v_112 != 0) {
               fx_str_t* v_113 = &_fx_g12Options__opt.build_rootdir;
               fx_str_t* bdir_0 = &v_112->hd;
               FX_FREE_STR(v_113);
               fx_copy_str(bdir_0, v_113);
               FX_COPY_PTR(v_112->tl, &v_32);
               goto _fx_endmatch_3;
            }
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_63 = FX_MAKE_STR("-c++");
         if (fx_streq(&args_1->hd, &slit_63)) {
            bool* v_114 = &_fx_g12Options__opt.compile_by_cpp;
            *v_114 = true;
            FX_COPY_PTR(args_1->tl, &v_32);
            goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_64 = FX_MAKE_STR("-cflags");
         if (fx_streq(&args_1->hd, &slit_64)) {
            _fx_LS v_115 = args_1->tl;
            if (v_115 != 0) {
               fx_str_t v_116 = {0};
               fx_str_t v_117 = {0};
               fx_str_t v_118 = {0};
               fx_str_t* cflags_0 = &v_115->hd;
               fx_copy_str(&_fx_g12Options__opt.cflags, &v_116);
               if (FX_STR_LENGTH(v_116) == 0) {
                  fx_copy_str(cflags_0, &v_117);
               }
               else {
                  fx_copy_str(&_fx_g12Options__opt.cflags, &v_118);
                  fx_str_t slit_65 = FX_MAKE_STR(" ");
                  {
                     const fx_str_t strs_8[] = { v_118, slit_65, *cflags_0 };
                     FX_CALL(fx_strjoin(0, 0, 0, strs_8, 3, &v_117), _fx_catch_9);
                  }
               }
               fx_str_t* v_119 = &_fx_g12Options__opt.cflags;
               FX_FREE_STR(v_119);
               fx_copy_str(&v_117, v_119);
               FX_COPY_PTR(v_115->tl, &v_32);

            _fx_catch_9: ;
               FX_FREE_STR(&v_118);
               FX_FREE_STR(&v_117);
               FX_FREE_STR(&v_116);
               goto _fx_endmatch_3;
            }
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_66 = FX_MAKE_STR("-clibs");
         if (fx_streq(&args_1->hd, &slit_66)) {
            _fx_LS v_120 = args_1->tl;
            if (v_120 != 0) {
               fx_str_t v_121 = {0};
               fx_str_t v_122 = {0};
               fx_str_t v_123 = {0};
               fx_str_t* clibs_0 = &v_120->hd;
               fx_copy_str(&_fx_g12Options__opt.clibs, &v_121);
               if (FX_STR_LENGTH(v_121) == 0) {
                  fx_copy_str(clibs_0, &v_122);
               }
               else {
                  fx_copy_str(&_fx_g12Options__opt.clibs, &v_123);
                  fx_str_t slit_67 = FX_MAKE_STR(" ");
                  {
                     const fx_str_t strs_9[] = { v_123, slit_67, *clibs_0 };
                     FX_CALL(fx_strjoin(0, 0, 0, strs_9, 3, &v_122), _fx_catch_10);
                  }
               }
               fx_str_t* v_124 = &_fx_g12Options__opt.clibs;
               FX_FREE_STR(v_124);
               fx_copy_str(&v_122, v_124);
               FX_COPY_PTR(v_120->tl, &v_32);

            _fx_catch_10: ;
               FX_FREE_STR(&v_123);
               FX_FREE_STR(&v_122);
               FX_FREE_STR(&v_121);
               goto _fx_endmatch_3;
            }
         }
      }
      bool res_2;
      if (args_1 != 0) {
         fx_str_t slit_68 = FX_MAKE_STR("-h");
         if (fx_streq(&args_1->hd, &slit_68)) {
            res_2 = true; goto _fx_endmatch_1;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_69 = FX_MAKE_STR("-help");
         if (fx_streq(&args_1->hd, &slit_69)) {
            res_2 = true; goto _fx_endmatch_1;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_70 = FX_MAKE_STR("--help");
         if (fx_streq(&args_1->hd, &slit_70)) {
            res_2 = true; goto _fx_endmatch_1;
         }
      }
      res_2 = false;

   _fx_endmatch_1: ;
      FX_CHECK_EXN(_fx_catch_12);
      if (res_2) {
         prhelp_0 = 2; goto _fx_endmatch_3;
      }
      bool res_3;
      if (args_1 != 0) {
         fx_str_t slit_71 = FX_MAKE_STR("-v");
         if (fx_streq(&args_1->hd, &slit_71)) {
            res_3 = true; goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_72 = FX_MAKE_STR("-version");
         if (fx_streq(&args_1->hd, &slit_72)) {
            res_3 = true; goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_73 = FX_MAKE_STR("--version");
         if (fx_streq(&args_1->hd, &slit_73)) {
            res_3 = true; goto _fx_endmatch_2;
         }
      }
      res_3 = false;

   _fx_endmatch_2: ;
      FX_CHECK_EXN(_fx_catch_12);
      if (res_3) {
         prver_0 = true; goto _fx_endmatch_3;
      }
      if (args_1 != 0) {
         fx_str_t slit_74 = FX_MAKE_STR("--");
         if (fx_streq(&args_1->hd, &slit_74)) {
            _fx_LS* v_125 = &_fx_g12Options__opt.app_args;
            _fx_LS* next_0 = &args_1->tl;
            _fx_free_LS(v_125);
            FX_COPY_PTR(*next_0, v_125);
            goto _fx_endmatch_3;
         }
      }
      if (args_1 != 0) {
         _fx_LS v_126 = 0;
         fx_str_t v_127 = {0};
         fx_str_t v_128 = {0};
         fx_str_t v_129 = {0};
         fx_str_t v_130 = {0};
         fx_str_t v_131 = {0};
         fx_str_t v_132 = {0};
         fx_str_t v_133 = {0};
         _fx_LS v_134 = 0;
         fx_str_t v_135 = {0};
         fx_str_t v_136 = {0};
         fx_str_t* a_0 = &args_1->hd;
         bool v_137;
         fx_str_t slit_75 = FX_MAKE_STR("-");
         v_137 = _fx_M6StringFM10startswithB2SS(a_0, &slit_75, 0);
         if (v_137) {
            fx_str_t slit_76 = FX_MAKE_STR("-clibs");
            FX_CALL(_fx_cons_LS(&slit_76, 0, true, &v_126), _fx_catch_11);
            fx_str_t slit_77 = FX_MAKE_STR("-cflags");
            FX_CALL(_fx_cons_LS(&slit_77, v_126, false, &v_126), _fx_catch_11);
            fx_str_t slit_78 = FX_MAKE_STR("-B");
            FX_CALL(_fx_cons_LS(&slit_78, v_126, false, &v_126), _fx_catch_11);
            fx_str_t slit_79 = FX_MAKE_STR("-o");
            FX_CALL(_fx_cons_LS(&slit_79, v_126, false, &v_126), _fx_catch_11);
            fx_str_t slit_80 = FX_MAKE_STR("-inline-threshold");
            FX_CALL(_fx_cons_LS(&slit_80, v_126, false, &v_126), _fx_catch_11);
            bool v_138;
            FX_CALL(_fx_M7OptionsFM3memB2LSS(v_126, a_0, &v_138, 0), _fx_catch_11);
            if (v_138) {
               fx_str_t slit_81 = FX_MAKE_STR("[31;1merror:[0m");
               FX_CALL(_fx_M7OptionsFM6stringS1S(&slit_81, &v_127, 0), _fx_catch_11);
               FX_CALL(_fx_M7OptionsFM6stringS1S(a_0, &v_128, 0), _fx_catch_11);
               fx_str_t slit_82 = FX_MAKE_STR(" option ");
               fx_str_t slit_83 = FX_MAKE_STR(" needs an argument");
               {
                  const fx_str_t strs_10[] = { v_127, slit_82, v_128, slit_83 };
                  FX_CALL(fx_strjoin(0, 0, 0, strs_10, 4, &v_129), _fx_catch_11);
               }
               FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_129, 0), _fx_catch_11);
            }
            else {
               fx_str_t slit_84 = FX_MAKE_STR("[31;1merror:[0m");
               FX_CALL(_fx_M7OptionsFM6stringS1S(&slit_84, &v_130, 0), _fx_catch_11);
               FX_CALL(_fx_M7OptionsFM6stringS1S(a_0, &v_131, 0), _fx_catch_11);
               fx_str_t slit_85 = FX_MAKE_STR(" unrecognized option ");
               {
                  const fx_str_t strs_11[] = { v_130, slit_85, v_131 };
                  FX_CALL(fx_strjoin(0, 0, 0, strs_11, 3, &v_132), _fx_catch_11);
               }
               FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_132, 0), _fx_catch_11);
            }
            ok_0 = false;
         }
         else if (FX_STR_LENGTH(inputfile_0) == 0) {
            FX_FREE_STR(&inputfile_0); fx_copy_str(a_0, &inputfile_0); FX_COPY_PTR(args_1->tl, &v_32);
         }
         else {
            fx_str_t slit_86 = FX_MAKE_STR("[31;1merror:[0m");
            FX_CALL(_fx_M7OptionsFM6stringS1S(&slit_86, &v_133, 0), _fx_catch_11);
            FX_CALL(_fx_cons_LS(a_0, 0, true, &v_134), _fx_catch_11);
            FX_CALL(_fx_cons_LS(&inputfile_0, v_134, false, &v_134), _fx_catch_11);
            FX_CALL(_fx_M7OptionsFM6stringS1LS(v_134, &v_135, 0), _fx_catch_11);
            fx_str_t slit_87 = FX_MAKE_STR(" more than one input file is specified: ");
            {
               const fx_str_t strs_12[] = { v_133, slit_87, v_135 };
               FX_CALL(fx_strjoin(0, 0, 0, strs_12, 3, &v_136), _fx_catch_11);
            }
            FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_136, 0), _fx_catch_11);
            ok_0 = false;
         }

      _fx_catch_11: ;
         FX_FREE_STR(&v_136);
         FX_FREE_STR(&v_135);
         if (v_134) {
            _fx_free_LS(&v_134);
         }
         FX_FREE_STR(&v_133);
         FX_FREE_STR(&v_132);
         FX_FREE_STR(&v_131);
         FX_FREE_STR(&v_130);
         FX_FREE_STR(&v_129);
         FX_FREE_STR(&v_128);
         FX_FREE_STR(&v_127);
         if (v_126) {
            _fx_free_LS(&v_126);
         }
         goto _fx_endmatch_3;
      }
      FX_FAST_THROW(FX_EXN_NoMatchError, _fx_catch_12);

   _fx_endmatch_3: ;
      FX_CHECK_EXN(_fx_catch_12);
      _fx_free_LS(&args_0);
      FX_COPY_PTR(v_32, &args_0);

   _fx_catch_12: ;
      if (v_32) {
         _fx_free_LS(&v_32);
      }
      if (args_1) {
         _fx_free_LS(&args_1);
      }
      FX_CHECK_EXN(_fx_cleanup);
   }
   int_ v_139 = _fx_g12Options__opt.optim_iters;
   if (v_139 <= 0) {
      int_ v_140 = _fx_g12Options__opt.optimize_level;
      int_ t_6;
      if (v_140 >= 3) {
         t_6 = 3;
      }
      else {
         t_6 = 2;
      }
      int_* v_141 = &_fx_g12Options__opt.optim_iters;
      *v_141 = t_6;
   }
   int_ v_142 = _fx_g12Options__opt.optim_iters;
   int_ res_4;
   FX_CALL(_fx_M7OptionsFM3maxi2ii(v_142, 2, &res_4, 0), _fx_cleanup);
   int_* v_143 = &_fx_g12Options__opt.optim_iters;
   *v_143 = res_4;
   bool t_7;
   if (!prver_0) {
      t_7 = prhelp_0 == 0;
   }
   else {
      t_7 = false;
   }
   bool t_8;
   if (t_7) {
      t_8 = ok_0;
   }
   else {
      t_8 = false;
   }
   if (t_8) {
      if (FX_STR_LENGTH(inputfile_0) == 0) {
         FX_CALL(_fx_M7OptionsFM2tlLS1LS(_fx_g9Sys__argv, &v_1, 0), _fx_cleanup);
         if (v_1 != 0) {
            fx_str_t slit_88 = FX_MAKE_STR("[31;1merror:[0m");
            FX_CALL(_fx_M7OptionsFM6stringS1S(&slit_88, &v_2, 0), _fx_cleanup);
            fx_str_t slit_89 = FX_MAKE_STR(" input file name is missing");
            {
               const fx_str_t strs_13[] = { v_2, slit_89 };
               FX_CALL(fx_strjoin(0, 0, 0, strs_13, 2, &v_3), _fx_cleanup);
            }
            FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_3, 0), _fx_cleanup);
            ok_0 = false;
         }
         else {
            prhelp_0 = 1;
         }
      }
      bool v_144;
      bool t_9;
      if (_fx_g12Options__opt.run_app) {
         t_9 = true;
      }
      else {
         t_9 = _fx_g12Options__opt.compile_by_cpp;
      }
      if (t_9) {
         bool v_145 = _fx_g12Options__opt.gen_c; v_144 = !v_145;
      }
      else {
         v_144 = false;
      }
      if (v_144) {
         fx_str_t slit_90 = FX_MAKE_STR("[31;1merror:[0m");
         FX_CALL(_fx_M7OptionsFM6stringS1S(&slit_90, &v_4, 0), _fx_cleanup);
         fx_str_t slit_91 = FX_MAKE_STR(" -no-c option cannot be used together with -run or -c++");
         {
            const fx_str_t strs_14[] = { v_4, slit_91 };
            FX_CALL(fx_strjoin(0, 0, 0, strs_14, 2, &v_5), _fx_cleanup);
         }
         FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_5, 0), _fx_cleanup);
         ok_0 = false;
      }
   }
   if (prver_0) {
      FX_CALL(_fx_M7OptionsFM6stringS1S(&_fx_g21__ficus_version_str__, &v_6, 0), _fx_cleanup);
      FX_CALL(_fx_M7OptionsFM6stringS1S(&_fx_g20__ficus_git_commit__, &v_7, 0), _fx_cleanup);
      fx_str_t slit_92 = FX_MAKE_STR("Ficus version: ");
      fx_str_t slit_93 = FX_MAKE_STR(" (git commit: ");
      fx_str_t slit_94 = FX_MAKE_STR(")");
      {
         const fx_str_t strs_15[] = { slit_92, v_6, slit_93, v_7, slit_94 };
         FX_CALL(fx_strjoin(0, 0, 0, strs_15, 5, &v_8), _fx_cleanup);
      }
      FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_8, 0), _fx_cleanup);
      FX_CALL(_fx_g11Sys__osname.fp(true, &v_9, _fx_g11Sys__osname.fcv), _fx_cleanup);
      FX_CALL(_fx_M7OptionsFM6stringS1S(&v_9, &v_10, 0), _fx_cleanup);
      fx_str_t slit_95 = FX_MAKE_STR("Platform: ");
      {
         const fx_str_t strs_16[] = { slit_95, v_10 };
         FX_CALL(fx_strjoin(0, 0, 0, strs_16, 2, &v_11), _fx_cleanup);
      }
      FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_11, 0), _fx_cleanup);
      FX_CALL(_fx_M3SysFM10cc_versionS0(&v_12, 0), _fx_cleanup);
      FX_CALL(_fx_M7OptionsFM6stringS1S(&v_12, &v_13, 0), _fx_cleanup);
      fx_str_t slit_96 = FX_MAKE_STR("C/C++ Compiler: ");
      {
         const fx_str_t strs_17[] = { slit_96, v_13 };
         FX_CALL(fx_strjoin(0, 0, 0, strs_17, 2, &v_14), _fx_cleanup);
      }
      FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_14, 0), _fx_cleanup);
      *fx_result = false;
   }
   else if (prhelp_0 > 0) {
      FX_CALL(_fx_M7OptionsFM10print_helpv1B(prhelp_0 > 1, 0), _fx_cleanup); *fx_result = false;
   }
   else if (ok_0) {
      int_ v_146 = _fx_g12Options__opt.optimize_level;
      if (v_146 == 0) {
         int_* v_147 = &_fx_g12Options__opt.inline_thresh; *v_147 = 1;
      }
      FX_CALL(_fx_M8FilenameFM9normalizeS2SS(&curr_dir_0, &inputfile_0, &v_15, 0), _fx_cleanup);
      fx_str_t* v_148 = &_fx_g12Options__opt.filename;
      FX_FREE_STR(v_148);
      fx_copy_str(&v_15, v_148);
      fx_copy_str(&_fx_g12Options__opt.filename, &v_16);
      FX_CALL(_fx_M8FilenameFM8basenameS1S(&v_16, &default_output_name_0, 0), _fx_cleanup);
      FX_CALL(_fx_M8FilenameFM16remove_extensionS1S(&default_output_name_0, &default_output_name_1, 0), _fx_cleanup);
      fx_copy_str(&_fx_g12Options__opt.build_rootdir, &v_17);
      FX_CALL(_fx_M8FilenameFM9normalizeS2SS(&curr_dir_0, &v_17, &v_18, 0), _fx_cleanup);
      fx_str_t* v_149 = &_fx_g12Options__opt.build_rootdir;
      FX_FREE_STR(v_149);
      fx_copy_str(&v_18, v_149);
      fx_copy_str(&_fx_g12Options__opt.build_rootdir, &v_19);
      fx_str_t slit_97 = FX_MAKE_STR("__fxbuild__");
      FX_CALL(_fx_M8FilenameFM9normalizeS2SS(&v_19, &slit_97, &v_20, 0), _fx_cleanup);
      fx_str_t* v_150 = &_fx_g12Options__opt.build_rootdir;
      FX_FREE_STR(v_150);
      fx_copy_str(&v_20, v_150);
      fx_copy_str(&_fx_g12Options__opt.output_name, &v_21);
      if (FX_STR_LENGTH(v_21) != 0) {
         fx_copy_str(&_fx_g12Options__opt.output_name, &v_22);
      }
      else {
         fx_copy_str(&default_output_name_1, &v_22);
      }
      fx_str_t* v_151 = &_fx_g12Options__opt.app_filename;
      FX_FREE_STR(v_151);
      fx_copy_str(&v_22, v_151);
      fx_copy_str(&_fx_g12Options__opt.build_rootdir, &v_23);
      fx_copy_str(&_fx_g12Options__opt.app_filename, &v_24);
      FX_CALL(_fx_M8FilenameFM8basenameS1S(&v_24, &v_25, 0), _fx_cleanup);
      FX_CALL(_fx_M8FilenameFM9normalizeS2SS(&v_23, &v_25, &v_26, 0), _fx_cleanup);
      fx_str_t* v_152 = &_fx_g12Options__opt.build_dir;
      FX_FREE_STR(v_152);
      fx_copy_str(&v_26, v_152);
      fx_copy_str(&_fx_g12Options__opt.output_name, &v_27);
      if (FX_STR_LENGTH(v_27) == 0) {
         fx_copy_str(&_fx_g12Options__opt.build_dir, &v_28);
         fx_copy_str(&_fx_g12Options__opt.app_filename, &v_29);
         FX_CALL(_fx_M8FilenameFM9normalizeS2SS(&v_28, &v_29, &v_30, 0), _fx_cleanup);
         fx_str_t* v_153 = &_fx_g12Options__opt.app_filename;
         FX_FREE_STR(v_153);
         fx_copy_str(&v_30, v_153);
      }
      *fx_result = true;
   }
   else {
      *fx_result = false;
   }

_fx_cleanup: ;
   _fx_free_R18Options__options_t(&v_0);
   FX_FREE_STR(&curr_dir_0);
   if (args_0) {
      _fx_free_LS(&args_0);
   }
   FX_FREE_STR(&inputfile_0);
   if (v_1) {
      _fx_free_LS(&v_1);
   }
   FX_FREE_STR(&v_2);
   FX_FREE_STR(&v_3);
   FX_FREE_STR(&v_4);
   FX_FREE_STR(&v_5);
   FX_FREE_STR(&v_6);
   FX_FREE_STR(&v_7);
   FX_FREE_STR(&v_8);
   FX_FREE_STR(&v_9);
   FX_FREE_STR(&v_10);
   FX_FREE_STR(&v_11);
   FX_FREE_STR(&v_12);
   FX_FREE_STR(&v_13);
   FX_FREE_STR(&v_14);
   FX_FREE_STR(&v_15);
   FX_FREE_STR(&v_16);
   FX_FREE_STR(&default_output_name_0);
   FX_FREE_STR(&default_output_name_1);
   FX_FREE_STR(&v_17);
   FX_FREE_STR(&v_18);
   FX_FREE_STR(&v_19);
   FX_FREE_STR(&v_20);
   FX_FREE_STR(&v_21);
   FX_FREE_STR(&v_22);
   FX_FREE_STR(&v_23);
   FX_FREE_STR(&v_24);
   FX_FREE_STR(&v_25);
   FX_FREE_STR(&v_26);
   FX_FREE_STR(&v_27);
   FX_FREE_STR(&v_28);
   FX_FREE_STR(&v_29);
   FX_FREE_STR(&v_30);
   return fx_status;
}

FX_EXTERN_C int fx_init_Options(void)
{
   int fx_status = 0;
   FX_CALL(_fx_M7OptionsFM15default_optionsRM9options_t0(&_fx_g12Options__opt, 0), _fx_cleanup);

_fx_cleanup: ;
   return fx_status;
}

FX_EXTERN_C void fx_deinit_Options(void)
{
   _fx_free_R18Options__options_t(&_fx_g12Options__opt);
}
