
// this is autogenerated file, do not edit it.
#include "ficus/ficus.h"

typedef struct _fx_LS_data_t {
   int_ rc;
   struct _fx_LS_data_t* tl;
   fx_str_t hd;
} _fx_LS_data_t, *_fx_LS;

typedef struct _fx_FPS1B {
   int (*fp)(bool, fx_str_t*, void*);
   fx_fcv_t* fcv;
} _fx_FPS1B;

typedef struct _fx_R18Options__options_t {
   struct _fx_LS_data_t* app_args;
   fx_str_t app_filename;
   bool arch64;
   bool force_rebuild;
   fx_str_t build_dir;
   fx_str_t build_rootdir;
   fx_str_t cflags;
   fx_str_t clibs;
   bool compile_by_cpp;
   fx_str_t filename;
   bool gen_c;
   struct _fx_LS_data_t* include_path;
   bool debug;
   int_ optim_iters;
   int_ inline_thresh;
   bool enable_openmp;
   bool relax;
   bool use_preamble;
   bool make_app;
   int_ optimize_level;
   fx_str_t output_name;
   bool print_ast0;
   bool print_ast;
   bool print_k0;
   bool print_k;
   bool print_tokens;
   bool run_app;
   bool verbose;
   bool W_unused;
} _fx_R18Options__options_t;

typedef struct {
   int_ rc;
   int_ data;
} _fx_E4Exit_data_t;

typedef struct {
   int_ rc;
   fx_str_t data;
} _fx_E4Fail_data_t;

static void _fx_free_LS(struct _fx_LS_data_t** dst)
{
   FX_FREE_LIST_IMPL(_fx_LS, fx_free_str);
}

static int _fx_cons_LS(fx_str_t* hd, struct _fx_LS_data_t* tl, bool addref_tl, struct _fx_LS_data_t** fx_result)
{
   FX_MAKE_LIST_IMPL(_fx_LS, fx_copy_str);
}

static void _fx_free_R18Options__options_t(struct _fx_R18Options__options_t* dst)
{
   _fx_free_LS(&dst->app_args);
   fx_free_str(&dst->app_filename);
   fx_free_str(&dst->build_dir);
   fx_free_str(&dst->build_rootdir);
   fx_free_str(&dst->cflags);
   fx_free_str(&dst->clibs);
   fx_free_str(&dst->filename);
   _fx_free_LS(&dst->include_path);
   fx_free_str(&dst->output_name);
}

static void _fx_copy_R18Options__options_t(struct _fx_R18Options__options_t* src, struct _fx_R18Options__options_t* dst)
{
   FX_COPY_PTR(src->app_args, &dst->app_args);
   fx_copy_str(&src->app_filename, &dst->app_filename);
   dst->arch64 = src->arch64;
   dst->force_rebuild = src->force_rebuild;
   fx_copy_str(&src->build_dir, &dst->build_dir);
   fx_copy_str(&src->build_rootdir, &dst->build_rootdir);
   fx_copy_str(&src->cflags, &dst->cflags);
   fx_copy_str(&src->clibs, &dst->clibs);
   dst->compile_by_cpp = src->compile_by_cpp;
   fx_copy_str(&src->filename, &dst->filename);
   dst->gen_c = src->gen_c;
   FX_COPY_PTR(src->include_path, &dst->include_path);
   dst->debug = src->debug;
   dst->optim_iters = src->optim_iters;
   dst->inline_thresh = src->inline_thresh;
   dst->enable_openmp = src->enable_openmp;
   dst->relax = src->relax;
   dst->use_preamble = src->use_preamble;
   dst->make_app = src->make_app;
   dst->optimize_level = src->optimize_level;
   fx_copy_str(&src->output_name, &dst->output_name);
   dst->print_ast0 = src->print_ast0;
   dst->print_ast = src->print_ast;
   dst->print_k0 = src->print_k0;
   dst->print_k = src->print_k;
   dst->print_tokens = src->print_tokens;
   dst->run_app = src->run_app;
   dst->verbose = src->verbose;
   dst->W_unused = src->W_unused;
}

static void _fx_make_R18Options__options_t(
   struct _fx_LS_data_t* r_app_args,
   fx_str_t* r_app_filename,
   bool r_arch64,
   bool r_force_rebuild,
   fx_str_t* r_build_dir,
   fx_str_t* r_build_rootdir,
   fx_str_t* r_cflags,
   fx_str_t* r_clibs,
   bool r_compile_by_cpp,
   fx_str_t* r_filename,
   bool r_gen_c,
   struct _fx_LS_data_t* r_include_path,
   bool r_debug,
   int_ r_optim_iters,
   int_ r_inline_thresh,
   bool r_enable_openmp,
   bool r_relax,
   bool r_use_preamble,
   bool r_make_app,
   int_ r_optimize_level,
   fx_str_t* r_output_name,
   bool r_print_ast0,
   bool r_print_ast,
   bool r_print_k0,
   bool r_print_k,
   bool r_print_tokens,
   bool r_run_app,
   bool r_verbose,
   bool r_W_unused,
   struct _fx_R18Options__options_t* fx_result)
{
   FX_COPY_PTR(r_app_args, &fx_result->app_args);
   fx_copy_str(r_app_filename, &fx_result->app_filename);
   fx_result->arch64 = r_arch64;
   fx_result->force_rebuild = r_force_rebuild;
   fx_copy_str(r_build_dir, &fx_result->build_dir);
   fx_copy_str(r_build_rootdir, &fx_result->build_rootdir);
   fx_copy_str(r_cflags, &fx_result->cflags);
   fx_copy_str(r_clibs, &fx_result->clibs);
   fx_result->compile_by_cpp = r_compile_by_cpp;
   fx_copy_str(r_filename, &fx_result->filename);
   fx_result->gen_c = r_gen_c;
   FX_COPY_PTR(r_include_path, &fx_result->include_path);
   fx_result->debug = r_debug;
   fx_result->optim_iters = r_optim_iters;
   fx_result->inline_thresh = r_inline_thresh;
   fx_result->enable_openmp = r_enable_openmp;
   fx_result->relax = r_relax;
   fx_result->use_preamble = r_use_preamble;
   fx_result->make_app = r_make_app;
   fx_result->optimize_level = r_optimize_level;
   fx_copy_str(r_output_name, &fx_result->output_name);
   fx_result->print_ast0 = r_print_ast0;
   fx_result->print_ast = r_print_ast;
   fx_result->print_k0 = r_print_k0;
   fx_result->print_k = r_print_k;
   fx_result->print_tokens = r_print_tokens;
   fx_result->run_app = r_run_app;
   fx_result->verbose = r_verbose;
   fx_result->W_unused = r_W_unused;
}

_fx_R18Options__options_t _fx_g12Options__opt = {0};
bool _fx_g18Options__is_arch64 = 
(bool)(sizeof(void*) > 4)
;
FX_EXTERN_C int _fx_F4reprS1S(fx_str_t* a_0, fx_str_t* fx_result, void* fx_fv);

FX_EXTERN_C int _fx_F12join_embraceS4SSSA1S(
   fx_str_t* begin,
   fx_str_t* end,
   fx_str_t* sep,
   fx_arr_t* strs,
   fx_str_t* fx_result,
   void* fx_fv);

FX_EXTERN_C void _fx_F12print_stringv1S(fx_str_t* a, void* fx_fv);

FX_EXTERN_C bool _fx_F6__eq__B2SS(fx_str_t* a, fx_str_t* b, void* fx_fv);

FX_EXTERN_C_VAL(struct _fx_LS_data_t* _fx_g9Sys__argv)
FX_EXTERN_C int _fx_M8FilenameFM8basenameS1S(fx_str_t* path_0, fx_str_t* fx_result, void* fx_fv);

FX_EXTERN_C_VAL(fx_str_t _fx_g21__ficus_version_str__)
FX_EXTERN_C int _fx_F6stringS1S(fx_str_t* a_0, fx_str_t* fx_result, void* fx_fv);

FX_EXTERN_C_VAL(fx_str_t _fx_g20__ficus_git_commit__)
FX_EXTERN_C int _fx_M3SysFM6getcwdS0(fx_str_t* fx_result, void* fx_fv);

FX_EXTERN_C int_ _fx_M6StringFM9to_int_ori2Si(fx_str_t* a, int_ defval, void* fx_fv);

FX_EXTERN_C bool _fx_M6StringFM10startswithB2SS(fx_str_t* s, fx_str_t* prefix, void* fx_fv);

FX_EXTERN_C_VAL(struct _fx_FPS1B _fx_g11Sys__osname)
FX_EXTERN_C int _fx_M3SysFM10cc_versionS0(fx_str_t* fx_result, void* fx_fv);

FX_EXTERN_C int _fx_M8FilenameFM9normalizeS2SS(fx_str_t* dir_0, fx_str_t* fname_0, fx_str_t* fx_result, void* fx_fv);

FX_EXTERN_C int _fx_M8FilenameFM16remove_extensionS1S(fx_str_t* path_0, fx_str_t* fx_result, void* fx_fv);

FX_EXTERN_C void _fx_M7OptionsFM5link2LS2LSLS(
   struct _fx_LS_data_t* l1,
   struct _fx_LS_data_t* l2,
   struct _fx_LS_data_t** fx_result,
   void* fx_fv)
{
   
fx_link_lists(l1, l2, fx_result);

}

FX_EXTERN_C int _fx_M7OptionsFM7__add__LS2LSLS(
   struct _fx_LS_data_t* l1_0,
   struct _fx_LS_data_t* l2_0,
   struct _fx_LS_data_t** fx_result,
   void* fx_fv)
{
   int fx_status = 0;
   if (l1_0 == 0) {
      FX_COPY_PTR(l2_0, fx_result);
   }
   else if (l2_0 == 0) {
      FX_COPY_PTR(l1_0, fx_result);
   }
   else {
      _fx_LS v_0 = 0;
      _fx_LS lstend_0 = 0;
      _fx_LS lst_0 = l1_0;
      for (; lst_0; lst_0 = lst_0->tl) {
         fx_str_t* x_0 = &lst_0->hd;
         _fx_LS node_0 = 0;
         FX_CALL(_fx_cons_LS(x_0, 0, false, &node_0), _fx_catch_0);
         FX_LIST_APPEND(v_0, lstend_0, node_0);

      _fx_catch_0: ;
         FX_CHECK_EXN(_fx_catch_1);
      }
      _fx_M7OptionsFM5link2LS2LSLS(v_0, l2_0, fx_result, 0);

   _fx_catch_1: ;
      if (v_0) {
         _fx_free_LS(&v_0);
      }
   }
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM6stringS1LS(struct _fx_LS_data_t* l_0, fx_str_t* fx_result, void* fx_fv)
{
   fx_arr_t v_0 = {0};
   int fx_status = 0;
   fx_str_t* dstptr_0 = 0;
   _fx_LS lst_0 = l_0;
   int_ len_0 = fx_list_length(lst_0);
   {
      const int_ shape_0[] = { len_0 };
      FX_CALL(fx_make_arr(1, shape_0, sizeof(fx_str_t), (fx_free_t)fx_free_str, (fx_copy_t)fx_copy_str, 0, &v_0), _fx_cleanup);
   }
   dstptr_0 = (fx_str_t*)v_0.data;
   for (; lst_0; lst_0 = lst_0->tl, dstptr_0++) {
      fx_str_t res_0 = {0};
      fx_str_t* x_0 = &lst_0->hd;
      FX_CALL(_fx_F4reprS1S(x_0, &res_0, 0), _fx_catch_0);
      fx_copy_str(&res_0, dstptr_0);

   _fx_catch_0: ;
      FX_FREE_STR(&res_0);
      FX_CHECK_EXN(_fx_cleanup);
   }
   fx_str_t slit_0 = FX_MAKE_STR("[");
   fx_str_t slit_1 = FX_MAKE_STR("]");
   fx_str_t slit_2 = FX_MAKE_STR(", ");
   FX_CALL(_fx_F12join_embraceS4SSSA1S(&slit_0, &slit_1, &slit_2, &v_0, fx_result, 0), _fx_cleanup);

_fx_cleanup: ;
   FX_FREE_ARR(&v_0);
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM3maxi2ii(int_ a_0, int_ b_0, int_* fx_result, void* fx_fv)
{
   int fx_status = 0;
   if (a_0 >= b_0) {
      *fx_result = a_0;
   }
   else {
      *fx_result = b_0;
   }
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM7printlnv1S(fx_str_t* a_0, void* fx_fv)
{
   int fx_status = 0;
   _fx_F12print_stringv1S(a_0, 0);
   fx_str_t slit_0 = FX_MAKE_STR("\n");
   _fx_F12print_stringv1S(&slit_0, 0);
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM2tlLS1LS(struct _fx_LS_data_t* __pat___0, struct _fx_LS_data_t** fx_result, void* fx_fv)
{
   int fx_status = 0;
   if (__pat___0 != 0) {
      FX_COPY_PTR(__pat___0->tl, fx_result);
   }
   else {
      FX_FAST_THROW(FX_EXN_NullListError, _fx_cleanup);
   }

_fx_cleanup: ;
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM3revLS1LS(struct _fx_LS_data_t* l_0, struct _fx_LS_data_t** fx_result, void* fx_fv)
{
   _fx_LS __fold_result___0 = 0;
   int fx_status = 0;
   _fx_LS lst_0 = l_0;
   for (; lst_0; lst_0 = lst_0->tl) {
      _fx_LS r_0 = 0;
      fx_str_t* a_0 = &lst_0->hd;
      FX_COPY_PTR(__fold_result___0, &r_0);
      FX_CALL(_fx_cons_LS(a_0, r_0, false, &r_0), _fx_catch_0);
      _fx_free_LS(&__fold_result___0);
      FX_COPY_PTR(r_0, &__fold_result___0);

   _fx_catch_0: ;
      if (r_0) {
         _fx_free_LS(&r_0);
      }
      FX_CHECK_EXN(_fx_cleanup);
   }
   FX_COPY_PTR(__fold_result___0, fx_result);

_fx_cleanup: ;
   if (__fold_result___0) {
      _fx_free_LS(&__fold_result___0);
   }
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM3memB2LSS(struct _fx_LS_data_t* l_0, fx_str_t* a_0, bool* fx_result, void* fx_fv)
{
   int fx_status = 0;
   bool __fold_result___0 = false;
   _fx_LS lst_0 = l_0;
   for (; lst_0; lst_0 = lst_0->tl) {
      fx_str_t* b_0 = &lst_0->hd;
      bool v_0 = _fx_F6__eq__B2SS(a_0, b_0, 0);
      if (v_0) {
         __fold_result___0 = true; FX_BREAK(_fx_catch_0);
      }

   _fx_catch_0: ;
      FX_CHECK_BREAK();
      FX_CHECK_EXN(_fx_cleanup);
   }
   *fx_result = __fold_result___0;

_fx_cleanup: ;
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM15default_optionsRM9options_t0(struct _fx_R18Options__options_t* fx_result, void* fx_fv)
{
   int fx_status = 0;
   fx_str_t slit_0 = FX_MAKE_STR("");
   fx_str_t slit_1 = FX_MAKE_STR("");
   fx_str_t slit_2 = FX_MAKE_STR("");
   fx_str_t slit_3 = FX_MAKE_STR("");
   fx_str_t slit_4 = FX_MAKE_STR("");
   fx_str_t slit_5 = FX_MAKE_STR("");
   fx_str_t slit_6 = FX_MAKE_STR("");
   _fx_make_R18Options__options_t(0, &slit_0, true, false, &slit_1, &slit_2, &slit_3, &slit_4, false, &slit_5, true, 0, false,
      0, 100, true, false, true, true, 1, &slit_6, false, false, false, false, false, false, false, true, fx_result);
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM10print_helpv1B(bool detailed_0, void* fx_fv)
{
   fx_str_t v_0 = {0};
   fx_str_t fxname_0 = {0};
   fx_str_t v_1 = {0};
   fx_str_t v_2 = {0};
   fx_str_t v_3 = {0};
   fx_str_t v_4 = {0};
   fx_str_t v_5 = {0};
   fx_str_t v_6 = {0};
   fx_str_t v_7 = {0};
   fx_str_t v_8 = {0};
   int fx_status = 0;
   if (_fx_g9Sys__argv != 0) {
      fx_copy_str(&_fx_g9Sys__argv->hd, &v_0);
   }
   else {
      FX_FAST_THROW(FX_EXN_NullListError, _fx_cleanup);
   }
   FX_CHECK_EXN(_fx_cleanup);
   FX_CALL(_fx_M8FilenameFM8basenameS1S(&v_0, &fxname_0, 0), _fx_cleanup);
   FX_CALL(_fx_F6stringS1S(&_fx_g21__ficus_version_str__, &v_1, 0), _fx_cleanup);
   FX_CALL(_fx_F6stringS1S(&_fx_g20__ficus_git_commit__, &v_2, 0), _fx_cleanup);
   fx_str_t slit_0 = FX_MAKE_STR("Ficus compiler v");
   fx_str_t slit_1 = FX_MAKE_STR(" (git ");
   fx_str_t slit_2 = FX_MAKE_STR(")");
   {
      const fx_str_t strs_0[] = { slit_0, v_1, slit_1, v_2, slit_2 };
      FX_CALL(fx_strjoin(0, 0, 0, strs_0, 5, &v_3), _fx_cleanup);
   }
   _fx_F12print_stringv1S(&v_3, 0);
   fx_str_t slit_3 = FX_MAKE_STR("\n");
   _fx_F12print_stringv1S(&slit_3, 0);
   if (!detailed_0) {
      FX_CALL(_fx_F6stringS1S(&fxname_0, &v_4, 0), _fx_cleanup);
      FX_CALL(_fx_F6stringS1S(&fxname_0, &v_5, 0), _fx_cleanup);
      fx_str_t slit_4 =
         FX_MAKE_STR("\n"
            U"Usage: ");
      fx_str_t slit_5 =
         FX_MAKE_STR(" [-pr-tokens | -pr-ast0 | -pr-ast | -pr-k0 | -pr-k | -no-c\n"
            U"    | -app | -run | -O0 | -O1 | -O3 | -inline-threshold <n> | -no-openmp\n"
            U"    | -o <output_name> | -I <incdir> | -B <build_root>\n"
            U"    | -c++ | -cflags <cflags> | -clibs <clibs>\n"
            U"    | -verbose | -h | -v ] <input_file>.fx [-- <app_args ...>]\n"
            U"\n"
            U"Run \'");
      fx_str_t slit_6 = FX_MAKE_STR(" -h\' to get more detailed help");
      {
         const fx_str_t strs_1[] = { slit_4, v_4, slit_5, v_5, slit_6 };
         FX_CALL(fx_strjoin(0, 0, 0, strs_1, 5, &v_6), _fx_cleanup);
      }
      _fx_F12print_stringv1S(&v_6, 0);
      fx_str_t slit_7 = FX_MAKE_STR("\n");
      _fx_F12print_stringv1S(&slit_7, 0);
   }
   else {
      FX_CALL(_fx_F6stringS1S(&fxname_0, &v_7, 0), _fx_cleanup);
      fx_str_t slit_8 =
         FX_MAKE_STR("\n"
            U"Usage: ");
      fx_str_t slit_9 =
         FX_MAKE_STR(" [options ...] <input_file.fx> [-- <app_args ...>]\n"
            U"\n"
            U"where options can be some of:\n"
            U"    -rebuild        Ignore cached files; rebuild everything from scratch\n"
            U"    -pr-tokens      Print all the tokens in parsed files\n"
            U"    -pr-ast0        Print AST right after parsing\n"
            U"    -pr-ast         Print typechecked AST of the parsed files\n"
            U"    -pr-k0          Print just generated K-form\n"
            U"    -pr-k           Print optimized K-form of the parsed files\n"
            U"                    (only a part of the generated K-form is retained\n"
            U"                    because of the dead code elimination step)\n"
            U"    -no-c           Do not generate C code\n"
            U"    -app            Build application (default mode)\n"
            U"    -run            Build application and run it\n"
            U"    -O0             Optimization level 0: disable all optimizations\n"
            U"                                         except for the most essential ones\n"
            U"    -O1             Optimization level 1 (default): enable most of the optimizations\n"
            U"    -O3             Optimization level 3: enable all optimizations\n"
            U"    -no-openmp      Disable OpenMP (OpenMP is enabled by default)\n"
            U"    -debug          Turn on debug information, disable optimizations\n"
            U"                    (but it can be overwritten with further -On)\n"
            U"    -optim-iters    The number of optimization iterations to perform (2 or 3 by default, depending on -O<n>)\n"
            U"    -inline-threshold  Inline threshold (100 by default); the higher it is,\n"
            U"                    the bigger functions are inlined;\n"
            U"                    --inline-thresh=0 disables inline expansion\n"
            U"    -relax          Do not require explicit typing of all global functions\' parameters\n"
            U"    -no-preamble    Do not auto-import \'Builtins\', \'List\', \'String\' and\n"
            U"                    a few other standard modules into each compiled module.\n"
            U"    -Wno-unused     Do not report errors about unused values/functions\n"
            U"    -o <output_name> Output file name (by default it matches the\n"
            U"                    input filename without .fx extension)\n"
            U"    -I <dir>        Add specified directory to the module search path\n"
            U"    -B <build_root> Specifies the parent directory <build_root> where subdirectory\n"
            U"                    <build_root>/__fxbuild__/<app_build_dir> with the generated files will be created.\n"
            U"                    By default, <build_root> is the current working directory.\n"
            U"    -c++            Use C++ compiler instead of C to compile the generated sources.\n"
            U"                    \'pragma \"c++\"\' in .fx file also instructs ficus compiler to use C++.\n"
            U"    -cflags <cflags> Pass the specified flags, e.g. \"-mavx2\", to C/C++ compiler.\n"
            U"                    If environment variable FICUS_CFLAGS is set,\n"
            U"                    its value is inserted before <cflags>\n"
            U"    -clibs <clibs>  Pass the specified libs/linker flags to C/C++ compiler.\n"
            U"                    If environment variable FICUS_LINK_LIBRARIES is set,\n"
            U"                    its value is inserted after <clibs>\n"
            U"    -verbose        Display various info during the build\n"
            U"    -h or -help or --help  Display this information\n"
            U"    -v or -version  Display information about compiler and the platform, then exit.\n"
            U"    --              Specify the application parameters when \'-run\' flag is used,\n"
            U"                    e.g. \'./ficus -run myprog.fx -- arg1 arg2\'\n");
      {
         const fx_str_t strs_2[] = { slit_8, v_7, slit_9 };
         FX_CALL(fx_strjoin(0, 0, 0, strs_2, 3, &v_8), _fx_cleanup);
      }
      _fx_F12print_stringv1S(&v_8, 0);
      fx_str_t slit_10 = FX_MAKE_STR("\n");
      _fx_F12print_stringv1S(&slit_10, 0);
   }

_fx_cleanup: ;
   FX_FREE_STR(&v_0);
   FX_FREE_STR(&fxname_0);
   FX_FREE_STR(&v_1);
   FX_FREE_STR(&v_2);
   FX_FREE_STR(&v_3);
   FX_FREE_STR(&v_4);
   FX_FREE_STR(&v_5);
   FX_FREE_STR(&v_6);
   FX_FREE_STR(&v_7);
   FX_FREE_STR(&v_8);
   return fx_status;
}

FX_EXTERN_C int _fx_M7OptionsFM13parse_optionsB0(bool* fx_result, void* fx_fv)
{
   _fx_R18Options__options_t v_0 = {0};
   fx_str_t curr_dir_0 = {0};
   _fx_LS args_0 = 0;
   fx_str_t inputfile_0 = {0};
   _fx_LS v_1 = 0;
   fx_str_t v_2 = {0};
   fx_str_t v_3 = {0};
   fx_str_t v_4 = {0};
   fx_str_t v_5 = {0};
   fx_str_t v_6 = {0};
   fx_str_t v_7 = {0};
   fx_str_t v_8 = {0};
   fx_str_t v_9 = {0};
   fx_str_t v_10 = {0};
   fx_str_t v_11 = {0};
   fx_str_t v_12 = {0};
   fx_str_t v_13 = {0};
   fx_str_t v_14 = {0};
   fx_str_t v_15 = {0};
   fx_str_t v_16 = {0};
   fx_str_t default_output_name_0 = {0};
   fx_str_t default_output_name_1 = {0};
   fx_str_t v_17 = {0};
   fx_str_t v_18 = {0};
   fx_str_t v_19 = {0};
   fx_str_t v_20 = {0};
   fx_str_t v_21 = {0};
   fx_str_t v_22 = {0};
   fx_str_t v_23 = {0};
   fx_str_t v_24 = {0};
   fx_str_t v_25 = {0};
   fx_str_t v_26 = {0};
   fx_str_t v_27 = {0};
   fx_str_t v_28 = {0};
   fx_str_t v_29 = {0};
   fx_str_t v_30 = {0};
   _fx_LS v_31 = 0;
   _fx_LS v_32 = 0;
   int fx_status = 0;
   FX_CALL(_fx_M7OptionsFM15default_optionsRM9options_t0(&v_0, 0), _fx_cleanup);
   _fx_free_R18Options__options_t(&_fx_g12Options__opt);
   _fx_copy_R18Options__options_t(&v_0, &_fx_g12Options__opt);
   _fx_g12Options__opt.arch64 = _fx_g18Options__is_arch64;
   FX_CALL(_fx_M3SysFM6getcwdS0(&curr_dir_0, 0), _fx_cleanup);
   FX_CALL(_fx_M7OptionsFM2tlLS1LS(_fx_g9Sys__argv, &args_0, 0), _fx_cleanup);
   fx_str_t slit_0 = FX_MAKE_STR("");
   fx_copy_str(&slit_0, &inputfile_0);
   int_ prhelp_0 = 0;
   bool prver_0 = false;
   bool ok_0 = true;
   while (args_0 != 0) {
      _fx_LS args_1 = 0;
      _fx_LS v_33 = 0;
      FX_COPY_PTR(args_0, &args_1);
      if (args_1 != 0) {
         fx_str_t slit_1 = FX_MAKE_STR("-no-preamble");
         if (fx_streq(&args_1->hd, &slit_1)) {
            _fx_g12Options__opt.use_preamble = false; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_2 = FX_MAKE_STR("-rebuild");
         if (fx_streq(&args_1->hd, &slit_2)) {
            _fx_g12Options__opt.force_rebuild = true; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_3 = FX_MAKE_STR("-pr-tokens");
         if (fx_streq(&args_1->hd, &slit_3)) {
            _fx_g12Options__opt.print_tokens = true; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_4 = FX_MAKE_STR("-pr-ast0");
         if (fx_streq(&args_1->hd, &slit_4)) {
            _fx_g12Options__opt.print_ast0 = true; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_5 = FX_MAKE_STR("-pr-ast");
         if (fx_streq(&args_1->hd, &slit_5)) {
            _fx_g12Options__opt.print_ast = true; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_6 = FX_MAKE_STR("-pr-k0");
         if (fx_streq(&args_1->hd, &slit_6)) {
            _fx_g12Options__opt.print_k0 = true; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_7 = FX_MAKE_STR("-pr-k");
         if (fx_streq(&args_1->hd, &slit_7)) {
            _fx_g12Options__opt.print_k = true; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_8 = FX_MAKE_STR("-no-c");
         if (fx_streq(&args_1->hd, &slit_8)) {
            _fx_g12Options__opt.gen_c = false; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_9 = FX_MAKE_STR("-app");
         if (fx_streq(&args_1->hd, &slit_9)) {
            _fx_g12Options__opt.make_app = true; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_10 = FX_MAKE_STR("-run");
         if (fx_streq(&args_1->hd, &slit_10)) {
            _fx_g12Options__opt.run_app = true; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_11 = FX_MAKE_STR("-O0");
         if (fx_streq(&args_1->hd, &slit_11)) {
            _fx_g12Options__opt.optimize_level = 0; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_12 = FX_MAKE_STR("-O1");
         if (fx_streq(&args_1->hd, &slit_12)) {
            _fx_g12Options__opt.optimize_level = 1; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_13 = FX_MAKE_STR("-O3");
         if (fx_streq(&args_1->hd, &slit_13)) {
            _fx_g12Options__opt.optimize_level = 3; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_14 = FX_MAKE_STR("-no-openmp");
         if (fx_streq(&args_1->hd, &slit_14)) {
            _fx_g12Options__opt.enable_openmp = false; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_15 = FX_MAKE_STR("-debug");
         if (fx_streq(&args_1->hd, &slit_15)) {
            _fx_g12Options__opt.debug = true; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_16 = FX_MAKE_STR("-optim-iters");
         if (fx_streq(&args_1->hd, &slit_16)) {
            _fx_LS v_34 = args_1->tl;
            if (v_34 != 0) {
               fx_str_t v_35 = {0};
               fx_str_t v_36 = {0};
               int_ i_0 = _fx_M6StringFM9to_int_ori2Si(&v_34->hd, -1, 0);
               if (i_0 >= 0) {
                  _fx_g12Options__opt.optim_iters = i_0; FX_COPY_PTR(v_34->tl, &v_33);
               }
               else {
                  fx_str_t slit_17 = FX_MAKE_STR("[31;1merror:[0m");
                  FX_CALL(_fx_F6stringS1S(&slit_17, &v_35, 0), _fx_catch_0);
                  fx_str_t slit_18 = FX_MAKE_STR(" invalid -optim-iters argument; must be a non-negative integer");
                  {
                     const fx_str_t strs_0[] = { v_35, slit_18 };
                     FX_CALL(fx_strjoin(0, 0, 0, strs_0, 2, &v_36), _fx_catch_0);
                  }
                  FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_36, 0), _fx_catch_0);
                  ok_0 = false;
               }

            _fx_catch_0: ;
               FX_FREE_STR(&v_36);
               FX_FREE_STR(&v_35);
               goto _fx_endmatch_2;
            }
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_19 = FX_MAKE_STR("-inline-threshold");
         if (fx_streq(&args_1->hd, &slit_19)) {
            _fx_LS v_37 = args_1->tl;
            if (v_37 != 0) {
               fx_str_t v_38 = {0};
               fx_str_t v_39 = {0};
               int_ i_1 = _fx_M6StringFM9to_int_ori2Si(&v_37->hd, -1, 0);
               if (i_1 >= 0) {
                  _fx_g12Options__opt.optim_iters = i_1; FX_COPY_PTR(v_37->tl, &v_33);
               }
               else {
                  fx_str_t slit_20 = FX_MAKE_STR("[31;1merror:[0m");
                  FX_CALL(_fx_F6stringS1S(&slit_20, &v_38, 0), _fx_catch_1);
                  fx_str_t slit_21 = FX_MAKE_STR(" invalid -inline-threshold argument; must be a non-negative integer");
                  {
                     const fx_str_t strs_1[] = { v_38, slit_21 };
                     FX_CALL(fx_strjoin(0, 0, 0, strs_1, 2, &v_39), _fx_catch_1);
                  }
                  FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_39, 0), _fx_catch_1);
                  ok_0 = false;
               }

            _fx_catch_1: ;
               FX_FREE_STR(&v_39);
               FX_FREE_STR(&v_38);
               goto _fx_endmatch_2;
            }
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_22 = FX_MAKE_STR("-relax");
         if (fx_streq(&args_1->hd, &slit_22)) {
            _fx_g12Options__opt.relax = true; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_23 = FX_MAKE_STR("-Wno-unused");
         if (fx_streq(&args_1->hd, &slit_23)) {
            _fx_g12Options__opt.W_unused = false; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_24 = FX_MAKE_STR("-verbose");
         if (fx_streq(&args_1->hd, &slit_24)) {
            _fx_g12Options__opt.verbose = true; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_25 = FX_MAKE_STR("-o");
         if (fx_streq(&args_1->hd, &slit_25)) {
            _fx_LS v_40 = args_1->tl;
            if (v_40 != 0) {
               fx_str_t* v_41 = &_fx_g12Options__opt.output_name;
               fx_str_t* oname_0 = &v_40->hd;
               FX_FREE_STR(v_41);
               fx_copy_str(oname_0, v_41);
               FX_COPY_PTR(v_40->tl, &v_33);
               goto _fx_endmatch_2;
            }
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_26 = FX_MAKE_STR("-I");
         if (fx_streq(&args_1->hd, &slit_26)) {
            _fx_LS v_42 = args_1->tl;
            if (v_42 != 0) {
               _fx_LS v_43 = 0;
               _fx_LS v_44 = 0;
               _fx_LS v_45 = 0;
               FX_COPY_PTR(_fx_g12Options__opt.include_path, &v_43);
               FX_CALL(_fx_cons_LS(&v_42->hd, 0, true, &v_44), _fx_catch_2);
               FX_CALL(_fx_M7OptionsFM7__add__LS2LSLS(v_43, v_44, &v_45, 0), _fx_catch_2);
               _fx_LS* v_46 = &_fx_g12Options__opt.include_path;
               _fx_free_LS(v_46);
               FX_COPY_PTR(v_45, v_46);
               FX_COPY_PTR(v_42->tl, &v_33);

            _fx_catch_2: ;
               if (v_45) {
                  _fx_free_LS(&v_45);
               }
               if (v_44) {
                  _fx_free_LS(&v_44);
               }
               if (v_43) {
                  _fx_free_LS(&v_43);
               }
               goto _fx_endmatch_2;
            }
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_27 = FX_MAKE_STR("-B");
         if (fx_streq(&args_1->hd, &slit_27)) {
            _fx_LS v_47 = args_1->tl;
            if (v_47 != 0) {
               fx_str_t* v_48 = &_fx_g12Options__opt.build_rootdir;
               fx_str_t* bdir_0 = &v_47->hd;
               FX_FREE_STR(v_48);
               fx_copy_str(bdir_0, v_48);
               FX_COPY_PTR(v_47->tl, &v_33);
               goto _fx_endmatch_2;
            }
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_28 = FX_MAKE_STR("-c++");
         if (fx_streq(&args_1->hd, &slit_28)) {
            _fx_g12Options__opt.compile_by_cpp = true; FX_COPY_PTR(args_1->tl, &v_33); goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_29 = FX_MAKE_STR("-cflags");
         if (fx_streq(&args_1->hd, &slit_29)) {
            _fx_LS v_49 = args_1->tl;
            if (v_49 != 0) {
               fx_str_t v_50 = {0};
               fx_str_t v_51 = {0};
               fx_str_t v_52 = {0};
               fx_str_t* cflags_0 = &v_49->hd;
               fx_copy_str(&_fx_g12Options__opt.cflags, &v_50);
               if (FX_STR_LENGTH(v_50) == 0) {
                  fx_copy_str(cflags_0, &v_51);
               }
               else {
                  fx_copy_str(&_fx_g12Options__opt.cflags, &v_52);
                  fx_str_t slit_30 = FX_MAKE_STR(" ");
                  {
                     const fx_str_t strs_2[] = { v_52, slit_30, *cflags_0 };
                     FX_CALL(fx_strjoin(0, 0, 0, strs_2, 3, &v_51), _fx_catch_3);
                  }
               }
               fx_str_t* v_53 = &_fx_g12Options__opt.cflags;
               FX_FREE_STR(v_53);
               fx_copy_str(&v_51, v_53);
               FX_COPY_PTR(v_49->tl, &v_33);

            _fx_catch_3: ;
               FX_FREE_STR(&v_52);
               FX_FREE_STR(&v_51);
               FX_FREE_STR(&v_50);
               goto _fx_endmatch_2;
            }
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_31 = FX_MAKE_STR("-clibs");
         if (fx_streq(&args_1->hd, &slit_31)) {
            _fx_LS v_54 = args_1->tl;
            if (v_54 != 0) {
               fx_str_t v_55 = {0};
               fx_str_t v_56 = {0};
               fx_str_t v_57 = {0};
               fx_str_t* clibs_0 = &v_54->hd;
               fx_copy_str(&_fx_g12Options__opt.clibs, &v_55);
               if (FX_STR_LENGTH(v_55) == 0) {
                  fx_copy_str(clibs_0, &v_56);
               }
               else {
                  fx_copy_str(&_fx_g12Options__opt.clibs, &v_57);
                  fx_str_t slit_32 = FX_MAKE_STR(" ");
                  {
                     const fx_str_t strs_3[] = { v_57, slit_32, *clibs_0 };
                     FX_CALL(fx_strjoin(0, 0, 0, strs_3, 3, &v_56), _fx_catch_4);
                  }
               }
               fx_str_t* v_58 = &_fx_g12Options__opt.clibs;
               FX_FREE_STR(v_58);
               fx_copy_str(&v_56, v_58);
               FX_COPY_PTR(v_54->tl, &v_33);

            _fx_catch_4: ;
               FX_FREE_STR(&v_57);
               FX_FREE_STR(&v_56);
               FX_FREE_STR(&v_55);
               goto _fx_endmatch_2;
            }
         }
      }
      bool res_0;
      if (args_1 != 0) {
         fx_str_t slit_33 = FX_MAKE_STR("-h");
         if (fx_streq(&args_1->hd, &slit_33)) {
            res_0 = true; goto _fx_endmatch_0;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_34 = FX_MAKE_STR("-help");
         if (fx_streq(&args_1->hd, &slit_34)) {
            res_0 = true; goto _fx_endmatch_0;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_35 = FX_MAKE_STR("--help");
         if (fx_streq(&args_1->hd, &slit_35)) {
            res_0 = true; goto _fx_endmatch_0;
         }
      }
      res_0 = false;

   _fx_endmatch_0: ;
      FX_CHECK_EXN(_fx_catch_6);
      if (res_0) {
         prhelp_0 = 2; goto _fx_endmatch_2;
      }
      bool res_1;
      if (args_1 != 0) {
         fx_str_t slit_36 = FX_MAKE_STR("-v");
         if (fx_streq(&args_1->hd, &slit_36)) {
            res_1 = true; goto _fx_endmatch_1;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_37 = FX_MAKE_STR("-version");
         if (fx_streq(&args_1->hd, &slit_37)) {
            res_1 = true; goto _fx_endmatch_1;
         }
      }
      if (args_1 != 0) {
         fx_str_t slit_38 = FX_MAKE_STR("--version");
         if (fx_streq(&args_1->hd, &slit_38)) {
            res_1 = true; goto _fx_endmatch_1;
         }
      }
      res_1 = false;

   _fx_endmatch_1: ;
      FX_CHECK_EXN(_fx_catch_6);
      if (res_1) {
         prver_0 = true; goto _fx_endmatch_2;
      }
      if (args_1 != 0) {
         fx_str_t slit_39 = FX_MAKE_STR("--");
         if (fx_streq(&args_1->hd, &slit_39)) {
            _fx_LS* v_59 = &_fx_g12Options__opt.app_args;
            _fx_LS* next_0 = &args_1->tl;
            _fx_free_LS(v_59);
            FX_COPY_PTR(*next_0, v_59);
            goto _fx_endmatch_2;
         }
      }
      if (args_1 != 0) {
         _fx_LS v_60 = 0;
         fx_str_t v_61 = {0};
         fx_str_t v_62 = {0};
         fx_str_t v_63 = {0};
         fx_str_t v_64 = {0};
         fx_str_t v_65 = {0};
         fx_str_t v_66 = {0};
         fx_str_t v_67 = {0};
         _fx_LS v_68 = 0;
         fx_str_t v_69 = {0};
         fx_str_t v_70 = {0};
         fx_str_t* a_0 = &args_1->hd;
         bool v_71;
         fx_str_t slit_40 = FX_MAKE_STR("-");
         v_71 = _fx_M6StringFM10startswithB2SS(a_0, &slit_40, 0);
         if (v_71) {
            fx_str_t slit_41 = FX_MAKE_STR("-clibs");
            FX_CALL(_fx_cons_LS(&slit_41, 0, true, &v_60), _fx_catch_5);
            fx_str_t slit_42 = FX_MAKE_STR("-cflags");
            FX_CALL(_fx_cons_LS(&slit_42, v_60, false, &v_60), _fx_catch_5);
            fx_str_t slit_43 = FX_MAKE_STR("-B");
            FX_CALL(_fx_cons_LS(&slit_43, v_60, false, &v_60), _fx_catch_5);
            fx_str_t slit_44 = FX_MAKE_STR("-o");
            FX_CALL(_fx_cons_LS(&slit_44, v_60, false, &v_60), _fx_catch_5);
            fx_str_t slit_45 = FX_MAKE_STR("-inline-threshold");
            FX_CALL(_fx_cons_LS(&slit_45, v_60, false, &v_60), _fx_catch_5);
            bool v_72;
            FX_CALL(_fx_M7OptionsFM3memB2LSS(v_60, a_0, &v_72, 0), _fx_catch_5);
            if (v_72) {
               fx_str_t slit_46 = FX_MAKE_STR("[31;1merror:[0m");
               FX_CALL(_fx_F6stringS1S(&slit_46, &v_61, 0), _fx_catch_5);
               FX_CALL(_fx_F6stringS1S(a_0, &v_62, 0), _fx_catch_5);
               fx_str_t slit_47 = FX_MAKE_STR(" option ");
               fx_str_t slit_48 = FX_MAKE_STR(" needs an argument");
               {
                  const fx_str_t strs_4[] = { v_61, slit_47, v_62, slit_48 };
                  FX_CALL(fx_strjoin(0, 0, 0, strs_4, 4, &v_63), _fx_catch_5);
               }
               FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_63, 0), _fx_catch_5);
            }
            else {
               fx_str_t slit_49 = FX_MAKE_STR("[31;1merror:[0m");
               FX_CALL(_fx_F6stringS1S(&slit_49, &v_64, 0), _fx_catch_5);
               FX_CALL(_fx_F6stringS1S(a_0, &v_65, 0), _fx_catch_5);
               fx_str_t slit_50 = FX_MAKE_STR(" unrecognized option ");
               {
                  const fx_str_t strs_5[] = { v_64, slit_50, v_65 };
                  FX_CALL(fx_strjoin(0, 0, 0, strs_5, 3, &v_66), _fx_catch_5);
               }
               FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_66, 0), _fx_catch_5);
            }
            ok_0 = false;
         }
         else if (FX_STR_LENGTH(inputfile_0) == 0) {
            FX_FREE_STR(&inputfile_0); fx_copy_str(a_0, &inputfile_0); FX_COPY_PTR(args_1->tl, &v_33);
         }
         else {
            fx_str_t slit_51 = FX_MAKE_STR("[31;1merror:[0m");
            FX_CALL(_fx_F6stringS1S(&slit_51, &v_67, 0), _fx_catch_5);
            FX_CALL(_fx_cons_LS(a_0, 0, true, &v_68), _fx_catch_5);
            FX_CALL(_fx_cons_LS(&inputfile_0, v_68, false, &v_68), _fx_catch_5);
            FX_CALL(_fx_M7OptionsFM6stringS1LS(v_68, &v_69, 0), _fx_catch_5);
            fx_str_t slit_52 = FX_MAKE_STR(" more than one input file is specified: ");
            {
               const fx_str_t strs_6[] = { v_67, slit_52, v_69 };
               FX_CALL(fx_strjoin(0, 0, 0, strs_6, 3, &v_70), _fx_catch_5);
            }
            FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_70, 0), _fx_catch_5);
            ok_0 = false;
         }

      _fx_catch_5: ;
         FX_FREE_STR(&v_70);
         FX_FREE_STR(&v_69);
         if (v_68) {
            _fx_free_LS(&v_68);
         }
         FX_FREE_STR(&v_67);
         FX_FREE_STR(&v_66);
         FX_FREE_STR(&v_65);
         FX_FREE_STR(&v_64);
         FX_FREE_STR(&v_63);
         FX_FREE_STR(&v_62);
         FX_FREE_STR(&v_61);
         if (v_60) {
            _fx_free_LS(&v_60);
         }
         goto _fx_endmatch_2;
      }
      FX_FAST_THROW(FX_EXN_NoMatchError, _fx_catch_6);

   _fx_endmatch_2: ;
      FX_CHECK_EXN(_fx_catch_6);
      _fx_free_LS(&args_0);
      FX_COPY_PTR(v_33, &args_0);

   _fx_catch_6: ;
      if (v_33) {
         _fx_free_LS(&v_33);
      }
      if (args_1) {
         _fx_free_LS(&args_1);
      }
      FX_CHECK_EXN(_fx_cleanup);
   }
   if (_fx_g12Options__opt.optim_iters <= 0) {
      int_ t_0;
      if (_fx_g12Options__opt.optimize_level == 3) {
         t_0 = 3;
      }
      else {
         t_0 = 2;
      }
      _fx_g12Options__opt.optim_iters = t_0;
   }
   int_ res_2;
   FX_CALL(_fx_M7OptionsFM3maxi2ii(_fx_g12Options__opt.optim_iters, 2, &res_2, 0), _fx_cleanup);
   _fx_g12Options__opt.optim_iters = res_2;
   bool t_1;
   if (!prver_0) {
      t_1 = prhelp_0 == 0;
   }
   else {
      t_1 = false;
   }
   bool t_2;
   if (t_1) {
      t_2 = ok_0;
   }
   else {
      t_2 = false;
   }
   if (t_2) {
      if (FX_STR_LENGTH(inputfile_0) == 0) {
         FX_CALL(_fx_M7OptionsFM2tlLS1LS(_fx_g9Sys__argv, &v_1, 0), _fx_cleanup);
         if (v_1 != 0) {
            fx_str_t slit_53 = FX_MAKE_STR("[31;1merror:[0m");
            FX_CALL(_fx_F6stringS1S(&slit_53, &v_2, 0), _fx_cleanup);
            fx_str_t slit_54 = FX_MAKE_STR(" input file name is missing");
            {
               const fx_str_t strs_7[] = { v_2, slit_54 };
               FX_CALL(fx_strjoin(0, 0, 0, strs_7, 2, &v_3), _fx_cleanup);
            }
            FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_3, 0), _fx_cleanup);
            ok_0 = false;
         }
         else {
            prhelp_0 = 1;
         }
      }
      bool t_3;
      if (_fx_g12Options__opt.run_app) {
         t_3 = true;
      }
      else {
         t_3 = _fx_g12Options__opt.compile_by_cpp;
      }
      bool t_4;
      if (t_3) {
         t_4 = !_fx_g12Options__opt.gen_c;
      }
      else {
         t_4 = false;
      }
      if (t_4) {
         fx_str_t slit_55 = FX_MAKE_STR("[31;1merror:[0m");
         FX_CALL(_fx_F6stringS1S(&slit_55, &v_4, 0), _fx_cleanup);
         fx_str_t slit_56 = FX_MAKE_STR(" -no-c option cannot be used together with -run or -c++");
         {
            const fx_str_t strs_8[] = { v_4, slit_56 };
            FX_CALL(fx_strjoin(0, 0, 0, strs_8, 2, &v_5), _fx_cleanup);
         }
         FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_5, 0), _fx_cleanup);
         ok_0 = false;
      }
   }
   if (prver_0) {
      FX_CALL(_fx_F6stringS1S(&_fx_g21__ficus_version_str__, &v_6, 0), _fx_cleanup);
      FX_CALL(_fx_F6stringS1S(&_fx_g20__ficus_git_commit__, &v_7, 0), _fx_cleanup);
      fx_str_t slit_57 = FX_MAKE_STR("Ficus version: ");
      fx_str_t slit_58 = FX_MAKE_STR(" (git commit: ");
      fx_str_t slit_59 = FX_MAKE_STR(")");
      {
         const fx_str_t strs_9[] = { slit_57, v_6, slit_58, v_7, slit_59 };
         FX_CALL(fx_strjoin(0, 0, 0, strs_9, 5, &v_8), _fx_cleanup);
      }
      FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_8, 0), _fx_cleanup);
      FX_CALL(_fx_g11Sys__osname.fp(true, &v_9, _fx_g11Sys__osname.fcv), _fx_cleanup);
      FX_CALL(_fx_F6stringS1S(&v_9, &v_10, 0), _fx_cleanup);
      fx_str_t slit_60 = FX_MAKE_STR("Plaform: ");
      {
         const fx_str_t strs_10[] = { slit_60, v_10 };
         FX_CALL(fx_strjoin(0, 0, 0, strs_10, 2, &v_11), _fx_cleanup);
      }
      FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_11, 0), _fx_cleanup);
      FX_CALL(_fx_M3SysFM10cc_versionS0(&v_12, 0), _fx_cleanup);
      FX_CALL(_fx_F6stringS1S(&v_12, &v_13, 0), _fx_cleanup);
      fx_str_t slit_61 = FX_MAKE_STR("C/C++ Compiler: ");
      {
         const fx_str_t strs_11[] = { slit_61, v_13 };
         FX_CALL(fx_strjoin(0, 0, 0, strs_11, 2, &v_14), _fx_cleanup);
      }
      FX_CALL(_fx_M7OptionsFM7printlnv1S(&v_14, 0), _fx_cleanup);
      *fx_result = false;
   }
   else if (prhelp_0 > 0) {
      FX_CALL(_fx_M7OptionsFM10print_helpv1B(prhelp_0 > 1, 0), _fx_cleanup); *fx_result = false;
   }
   else if (ok_0) {
      if (_fx_g12Options__opt.optimize_level == 0) {
         _fx_g12Options__opt.inline_thresh = 1;
      }
      FX_CALL(_fx_M8FilenameFM9normalizeS2SS(&curr_dir_0, &inputfile_0, &v_15, 0), _fx_cleanup);
      fx_str_t* v_73 = &_fx_g12Options__opt.filename;
      FX_FREE_STR(v_73);
      fx_copy_str(&v_15, v_73);
      fx_copy_str(&_fx_g12Options__opt.filename, &v_16);
      FX_CALL(_fx_M8FilenameFM8basenameS1S(&v_16, &default_output_name_0, 0), _fx_cleanup);
      FX_CALL(_fx_M8FilenameFM16remove_extensionS1S(&default_output_name_0, &default_output_name_1, 0), _fx_cleanup);
      fx_copy_str(&_fx_g12Options__opt.build_rootdir, &v_17);
      FX_CALL(_fx_M8FilenameFM9normalizeS2SS(&curr_dir_0, &v_17, &v_18, 0), _fx_cleanup);
      fx_str_t* v_74 = &_fx_g12Options__opt.build_rootdir;
      FX_FREE_STR(v_74);
      fx_copy_str(&v_18, v_74);
      fx_copy_str(&_fx_g12Options__opt.build_rootdir, &v_19);
      fx_str_t slit_62 = FX_MAKE_STR("__fxbuild__");
      FX_CALL(_fx_M8FilenameFM9normalizeS2SS(&v_19, &slit_62, &v_20, 0), _fx_cleanup);
      fx_str_t* v_75 = &_fx_g12Options__opt.build_rootdir;
      FX_FREE_STR(v_75);
      fx_copy_str(&v_20, v_75);
      fx_copy_str(&_fx_g12Options__opt.output_name, &v_21);
      if (FX_STR_LENGTH(v_21) != 0) {
         fx_copy_str(&_fx_g12Options__opt.output_name, &v_22);
      }
      else {
         fx_copy_str(&default_output_name_1, &v_22);
      }
      fx_str_t* v_76 = &_fx_g12Options__opt.app_filename;
      FX_FREE_STR(v_76);
      fx_copy_str(&v_22, v_76);
      fx_copy_str(&_fx_g12Options__opt.build_rootdir, &v_23);
      fx_copy_str(&_fx_g12Options__opt.app_filename, &v_24);
      FX_CALL(_fx_M8FilenameFM8basenameS1S(&v_24, &v_25, 0), _fx_cleanup);
      FX_CALL(_fx_M8FilenameFM9normalizeS2SS(&v_23, &v_25, &v_26, 0), _fx_cleanup);
      fx_str_t* v_77 = &_fx_g12Options__opt.build_dir;
      FX_FREE_STR(v_77);
      fx_copy_str(&v_26, v_77);
      fx_copy_str(&_fx_g12Options__opt.output_name, &v_27);
      if (FX_STR_LENGTH(v_27) == 0) {
         fx_copy_str(&_fx_g12Options__opt.build_dir, &v_28);
         fx_copy_str(&_fx_g12Options__opt.app_filename, &v_29);
         FX_CALL(_fx_M8FilenameFM9normalizeS2SS(&v_28, &v_29, &v_30, 0), _fx_cleanup);
         fx_str_t* v_78 = &_fx_g12Options__opt.app_filename;
         FX_FREE_STR(v_78);
         fx_copy_str(&v_30, v_78);
      }
      FX_COPY_PTR(_fx_g12Options__opt.app_args, &v_31);
      FX_CALL(_fx_M7OptionsFM3revLS1LS(v_31, &v_32, 0), _fx_cleanup);
      _fx_LS* v_79 = &_fx_g12Options__opt.app_args;
      _fx_free_LS(v_79);
      FX_COPY_PTR(v_32, v_79);
      *fx_result = true;
   }
   else {
      *fx_result = false;
   }

_fx_cleanup: ;
   _fx_free_R18Options__options_t(&v_0);
   FX_FREE_STR(&curr_dir_0);
   if (args_0) {
      _fx_free_LS(&args_0);
   }
   FX_FREE_STR(&inputfile_0);
   if (v_1) {
      _fx_free_LS(&v_1);
   }
   FX_FREE_STR(&v_2);
   FX_FREE_STR(&v_3);
   FX_FREE_STR(&v_4);
   FX_FREE_STR(&v_5);
   FX_FREE_STR(&v_6);
   FX_FREE_STR(&v_7);
   FX_FREE_STR(&v_8);
   FX_FREE_STR(&v_9);
   FX_FREE_STR(&v_10);
   FX_FREE_STR(&v_11);
   FX_FREE_STR(&v_12);
   FX_FREE_STR(&v_13);
   FX_FREE_STR(&v_14);
   FX_FREE_STR(&v_15);
   FX_FREE_STR(&v_16);
   FX_FREE_STR(&default_output_name_0);
   FX_FREE_STR(&default_output_name_1);
   FX_FREE_STR(&v_17);
   FX_FREE_STR(&v_18);
   FX_FREE_STR(&v_19);
   FX_FREE_STR(&v_20);
   FX_FREE_STR(&v_21);
   FX_FREE_STR(&v_22);
   FX_FREE_STR(&v_23);
   FX_FREE_STR(&v_24);
   FX_FREE_STR(&v_25);
   FX_FREE_STR(&v_26);
   FX_FREE_STR(&v_27);
   FX_FREE_STR(&v_28);
   FX_FREE_STR(&v_29);
   FX_FREE_STR(&v_30);
   if (v_31) {
      _fx_free_LS(&v_31);
   }
   if (v_32) {
      _fx_free_LS(&v_32);
   }
   return fx_status;
}

FX_EXTERN_C int fx_init_Options(void)
{
   int fx_status = 0;
   FX_CALL(_fx_M7OptionsFM15default_optionsRM9options_t0(&_fx_g12Options__opt, 0), _fx_cleanup);

_fx_cleanup: ;
   return fx_status;
}

FX_EXTERN_C void fx_deinit_Options(void)
{
   _fx_free_R18Options__options_t(&_fx_g12Options__opt);
}

