
// this is autogenerated file, do not edit it.
#include "ficus/ficus.h"

int _FX_EXN_E15Set__RBSetError = 0;
fx_exn_info_t _fx_E15Set__RBSetError_info = {  };
fx_exn_t _fx_E15Set__RBSetErrorv = {  };
FX_EXTERN_C int fx_init_Set(void)
{
   FX_REG_SIMPLE_EXN("Set.RBSetError", _FX_EXN_E15Set__RBSetError, _fx_E15Set__RBSetError_info, _fx_E15Set__RBSetErrorv);
   int fx_status = 0;
   return fx_status;
}

FX_EXTERN_C void fx_deinit_Set(void)
{

}

